import type { Tier } from './pricing-types'

import { TiersEnum } from './pricing-types'

export const tiers: Array<Tier> = [
  {
    key: TiersEnum.Basico,
    title: 'Básico',
    price: 'Precio personalizado',
    href: '/contact?plan=basico',
    featured: false,
    mostPopular: false,
    description: 'Ideal para condominios pequeños que están comenzando.',
    features: [
      'Hasta 50 unidades',
      'Gestión de cuotas y cobros',
      '1 administrador',
      'Sistema de avisos',
      'Soporte por email',
    ],
    buttonText: 'Solicitar cotización',
    buttonColor: 'default',
    buttonVariant: 'bordered',
  },
  {
    key: TiersEnum.Profesional,
    title: 'Profesional',
    description: 'La solución completa para administrar profesionalmente.',
    href: '/contact?plan=profesional',
    mostPopular: true,
    price: 'Precio personalizado',
    featured: false,
    features: [
      'Hasta 200 unidades',
      'Pagos en línea integrados',
      'Hasta 5 administradores',
      'Recordatorios automáticos',
      'Reportes y análisis avanzados',
      'Soporte prioritario',
    ],
    buttonText: 'Contactar ahora',
    buttonColor: 'primary',
    buttonVariant: 'solid',
  },
  {
    key: TiersEnum.Empresarial,
    title: 'Empresarial',
    href: '/contact?plan=empresarial',
    featured: true,
    mostPopular: false,
    description: 'Solución enterprise para administradoras con múltiples propiedades.',
    price: 'Precio personalizado',
    features: [
      'Unidades ilimitadas',
      'Administradores ilimitados',
      'Funcionalidades completas',
      'Integraciones personalizadas',
      'Capacitación y onboarding',
      'Soporte dedicado 24/7',
      'Manager de cuenta asignado',
    ],
    buttonText: 'Agendar reunión',
    buttonColor: 'default',
    buttonVariant: 'bordered',
  },
]
