import { describe, it, expect, beforeEach } from 'bun:test'
import { AllocatePaymentFIFOService } from '@services/billing-ledger/allocate-payment-fifo.service'

// ─── Helpers ───

function mockCharge(id: string, amount: string, opts: Record<string, unknown> = {}) {
  return {
    id,
    condominiumId: 'condo-1',
    chargeTypeId: 'ct-1',
    unitId: 'unit-1',
    amount,
    paidAmount: '0.00',
    balance: amount,
    status: 'pending',
    isCredit: false,
    isAutoGenerated: false,
    currencyId: 'cur-1',
    createdAt: new Date('2026-01-15'),
    ...opts,
  }
}

function interestCharge(id: string, amount: string, date: string) {
  return mockCharge(id, amount, {
    isAutoGenerated: true,
    chargeTypeId: 'ct-interest',
    createdAt: new Date(date),
  })
}

const createMockRepos = (charges: ReturnType<typeof mockCharge>[]) => {
  const updates: Array<{ id: string; data: Record<string, unknown> }> = []
  const allocations: Array<Record<string, unknown>> = []

  return {
    chargesRepo: {
      findPendingByUnitAndCondominium: async () => charges,
      update: async (id: string, data: Record<string, unknown>) => {
        updates.push({ id, data })
        return { ...charges.find(c => c.id === id)!, ...data }
      },
    } as never,
    allocationsRepo: {
      create: async (data: Record<string, unknown>) => {
        const alloc = { id: `alloc-${allocations.length + 1}`, allocatedAt: new Date(), ...data }
        allocations.push(alloc)
        return alloc
      },
    } as never,
    receiptsRepo: {
      update: async () => ({}),
    } as never,
    updates,
    allocations,
  }
}

describe('Allocation Strategies', () => {
  describe('FIFO (default)', () => {
    it('should allocate to oldest charge first', async () => {
      const charges = [
        mockCharge('old', '50.00', { createdAt: new Date('2026-01-01') }),
        mockCharge('new', '50.00', { createdAt: new Date('2026-03-01') }),
      ]
      const repos = createMockRepos(charges)
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '60.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations).toHaveLength(2)
        expect(repos.allocations[0]!.chargeId).toBe('old')
        expect(repos.allocations[0]!.allocatedAmount).toBe('50.00')
        expect(repos.allocations[1]!.chargeId).toBe('new')
        expect(repos.allocations[1]!.allocatedAmount).toBe('10.00')
      }
    })
  })

  describe('FIFO Interest First', () => {
    it('should allocate to interest charges before principal', async () => {
      const charges = [
        mockCharge('principal', '100.00', { createdAt: new Date('2026-01-01') }),
        interestCharge('interest', '10.00', '2026-02-01'),
      ]
      const repos = createMockRepos(charges)
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '15.00', strategy: 'fifo_interest_first',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations).toHaveLength(2)
        // Interest should be allocated first
        expect(repos.allocations[0]!.chargeId).toBe('interest')
        expect(repos.allocations[0]!.allocatedAmount).toBe('10.00')
        // Then principal with remaining
        expect(repos.allocations[1]!.chargeId).toBe('principal')
        expect(repos.allocations[1]!.allocatedAmount).toBe('5.00')
      }
    })

    it('should handle multiple interest charges sorted by date', async () => {
      const charges = [
        mockCharge('principal', '100.00', { createdAt: new Date('2026-01-01') }),
        interestCharge('interest-feb', '5.00', '2026-02-01'),
        interestCharge('interest-mar', '8.00', '2026-03-01'),
      ]
      const repos = createMockRepos(charges)
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '10.00', strategy: 'fifo_interest_first',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations).toHaveLength(2)
        // Feb interest first (older)
        expect(repos.allocations[0]!.chargeId).toBe('interest-feb')
        expect(repos.allocations[0]!.allocatedAmount).toBe('5.00')
        // Mar interest with remaining
        expect(repos.allocations[1]!.chargeId).toBe('interest-mar')
        expect(repos.allocations[1]!.allocatedAmount).toBe('5.00')
      }
    })
  })

  describe('Designated', () => {
    it('should allocate to all provided charges in order', async () => {
      // For designated strategy, the caller pre-filters the charges
      // The service still processes them in order
      const charges = [
        mockCharge('specific-charge', '75.00', { createdAt: new Date('2026-02-15') }),
      ]
      const repos = createMockRepos(charges)
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '75.00', strategy: 'designated',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations).toHaveLength(1)
        expect(repos.allocations[0]!.chargeId).toBe('specific-charge')
        expect(repos.allocations[0]!.allocatedAmount).toBe('75.00')
        expect(result.data.remaining).toBe('0.00')
      }
    })
  })

  describe('Edge cases', () => {
    it('should return remaining when payment exceeds all charges', async () => {
      const charges = [mockCharge('only', '30.00')]
      const repos = createMockRepos(charges)
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '100.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.remaining).toBe('70.00')
      }
    })

    it('should reject zero amount', async () => {
      const repos = createMockRepos([])
      const service = new AllocatePaymentFIFOService(repos.chargesRepo, repos.allocationsRepo, repos.receiptsRepo)

      const result = await service.execute({
        paymentId: 'pay-1', unitId: 'unit-1', condominiumId: 'condo-1',
        amount: '0.00', strategy: 'fifo',
      })

      expect(result.success).toBe(false)
    })
  })
})
