import { describe, it, expect, beforeEach } from 'bun:test'
import type { TCharge, TPaymentAllocation } from '@packages/domain'
import { AllocatePaymentFIFOService } from '@src/services/billing-ledger/allocate-payment-fifo.service'

const unitId = 'unit-001'
const condominiumId = 'channel-001'
const currencyId = 'currency-001'

function makeCharge(id: string, amount: string, paidAmount = '0', status = 'pending' as TCharge['status']): TCharge {
  const bal = (parseFloat(amount) - parseFloat(paidAmount)).toFixed(2)
  return {
    id, condominiumId: condominiumId, chargeTypeId: 'ct-1', unitId,
    receiptId: null, periodYear: 2026, periodMonth: 1,
    description: `Charge ${id}`, amount, isCredit: false, currencyId,
    status, paidAmount, balance: bal,
    sourceExpenseId: null, sourceChargeId: null, isAutoGenerated: false,
    metadata: null, createdBy: null,
    createdAt: new Date(), updatedAt: new Date(),
  }
}

describe('AllocatePaymentFIFOService', () => {
  let service: AllocatePaymentFIFOService
  let chargesState: Map<string, TCharge>
  let allocations: TPaymentAllocation[]
  let allocIdCounter: number

  beforeEach(() => {
    chargesState = new Map()
    allocations = []
    allocIdCounter = 0

    const mockChargesRepo = {
      findPendingByUnitAndCondominium: async () => {
        return Array.from(chargesState.values())
          .filter(c => c.status === 'pending' || c.status === 'partial')
          .sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime())
      },
      update: async (id: string, data: Partial<TCharge>) => {
        const existing = chargesState.get(id)!
        const updated = { ...existing, ...data }
        chargesState.set(id, updated)
        return updated
      },
    }

    const mockAllocationsRepo = {
      create: async (data: any) => {
        const alloc: TPaymentAllocation = {
          id: `alloc-${++allocIdCounter}`,
          paymentId: data.paymentId,
          chargeId: data.chargeId,
          allocatedAmount: data.allocatedAmount,
          allocatedAt: new Date(),
          reversed: false,
          reversedAt: null,
          createdBy: null,
        }
        allocations.push(alloc)
        return alloc
      },
    }

    const mockReceiptsRepo = {
      findByReceiptId: async () => null,
      update: async () => null,
    }

    service = new AllocatePaymentFIFOService(
      mockChargesRepo as never,
      mockAllocationsRepo as never,
      mockReceiptsRepo as never,
    )
  })

  describe('exact payment', () => {
    it('should fully pay a single charge', async () => {
      chargesState.set('c1', makeCharge('c1', '45.00'))

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '45.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations.length).toBe(1)
        expect(result.data.allocations[0]!.allocatedAmount).toBe('45.00')
        expect(result.data.remaining).toBe('0.00')
        expect(chargesState.get('c1')!.status).toBe('paid')
        expect(chargesState.get('c1')!.balance).toBe('0.00')
      }
    })
  })

  describe('partial payment', () => {
    it('should partially pay the oldest charge', async () => {
      chargesState.set('c1', makeCharge('c1', '45.00'))

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '20.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations.length).toBe(1)
        expect(result.data.allocations[0]!.allocatedAmount).toBe('20.00')
        expect(result.data.remaining).toBe('0.00')
        expect(chargesState.get('c1')!.status).toBe('partial')
        expect(chargesState.get('c1')!.paidAmount).toBe('20.00')
        expect(chargesState.get('c1')!.balance).toBe('25.00')
      }
    })
  })

  describe('payment covers multiple charges (FIFO)', () => {
    it('should allocate oldest first', async () => {
      const c1 = makeCharge('c1', '45.00')
      c1.createdAt = new Date('2026-01-05')
      const c2 = makeCharge('c2', '45.00')
      c2.createdAt = new Date('2026-02-05')
      const c3 = makeCharge('c3', '45.00')
      c3.createdAt = new Date('2026-03-05')

      chargesState.set('c1', c1)
      chargesState.set('c2', c2)
      chargesState.set('c3', c3)

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '100.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations.length).toBe(3)
        // c1: fully paid ($45)
        expect(result.data.allocations[0]!.allocatedAmount).toBe('45.00')
        expect(chargesState.get('c1')!.status).toBe('paid')
        // c2: fully paid ($45)
        expect(result.data.allocations[1]!.allocatedAmount).toBe('45.00')
        expect(chargesState.get('c2')!.status).toBe('paid')
        // c3: partially paid ($10)
        expect(result.data.allocations[2]!.allocatedAmount).toBe('10.00')
        expect(chargesState.get('c3')!.status).toBe('partial')
        expect(chargesState.get('c3')!.balance).toBe('35.00')
        // No remaining
        expect(result.data.remaining).toBe('0.00')
      }
    })
  })

  describe('overpayment (saldo a favor)', () => {
    it('should return remaining amount after covering all charges', async () => {
      chargesState.set('c1', makeCharge('c1', '45.00'))

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '100.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations.length).toBe(1)
        expect(result.data.remaining).toBe('55.00')
        expect(chargesState.get('c1')!.status).toBe('paid')
      }
    })
  })

  describe('no pending charges', () => {
    it('should return all as remaining', async () => {
      // No charges in state

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '100.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations.length).toBe(0)
        expect(result.data.remaining).toBe('100.00')
      }
    })
  })

  describe('charge already partially paid', () => {
    it('should only allocate to remaining balance', async () => {
      chargesState.set('c1', makeCharge('c1', '45.00', '20.00', 'partial'))

      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '25.00', strategy: 'fifo',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.allocations[0]!.allocatedAmount).toBe('25.00')
        expect(chargesState.get('c1')!.status).toBe('paid')
        expect(chargesState.get('c1')!.paidAmount).toBe('45.00')
        expect(chargesState.get('c1')!.balance).toBe('0.00')
      }
    })
  })

  describe('validation', () => {
    it('should reject amount <= 0', async () => {
      const result = await service.execute({
        paymentId: 'pay-1', unitId, condominiumId: condominiumId,
        amount: '0', strategy: 'fifo',
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.code).toBe('BAD_REQUEST')
      }
    })
  })
})
