import { describe, it, expect, beforeEach } from 'bun:test'
import type { TUnitLedgerEntry, TCharge } from '@packages/domain'
import { GetAccountStatementService } from '@src/services/billing-ledger/get-account-statement.service'

const unitId = 'unit-001'
const condominiumId = 'channel-001'
const currencyId = 'currency-001'

const mockEntries: TUnitLedgerEntry[] = [
  {
    id: 'e1', unitId, condominiumId: condominiumId, entryDate: '2026-01-05',
    entryType: 'debit', amount: '48500.00', currencyId, runningBalance: '48500.00',
    description: 'Recibo Ene 2026', referenceType: 'charge', referenceId: 'c1',
    paymentAmount: null, paymentCurrencyId: null, exchangeRateId: null, createdBy: null, createdAt: new Date(),
  },
  {
    id: 'e2', unitId, condominiumId: condominiumId, entryDate: '2026-01-15',
    entryType: 'credit', amount: '48500.00', currencyId, runningBalance: '0.00',
    description: 'Pago #REF123', referenceType: 'payment', referenceId: 'p1',
    paymentAmount: null, paymentCurrencyId: null, exchangeRateId: null, createdBy: null, createdAt: new Date(),
  },
  {
    id: 'e3', unitId, condominiumId: condominiumId, entryDate: '2026-02-05',
    entryType: 'debit', amount: '51200.00', currencyId, runningBalance: '51200.00',
    description: 'Recibo Feb 2026', referenceType: 'charge', referenceId: 'c2',
    paymentAmount: null, paymentCurrencyId: null, exchangeRateId: null, createdBy: null, createdAt: new Date(),
  },
]

const mockPendingCharges: TCharge[] = [
  {
    id: 'c2', condominiumId: condominiumId, chargeTypeId: 'ct1', unitId,
    receiptId: 'r2', periodYear: 2026, periodMonth: 2,
    description: 'Recibo Feb', amount: '51200.00', isCredit: false,
    currencyId, status: 'pending', paidAmount: '0', balance: '51200.00',
    sourceExpenseId: null, sourceChargeId: null, isAutoGenerated: false,
    metadata: null, createdBy: null, createdAt: new Date(), updatedAt: new Date(),
  },
]

describe('GetAccountStatementService', () => {
  let service: GetAccountStatementService

  beforeEach(() => {
    const mockLedgerRepo = {
      getLastEntryBefore: async () => null,
      getEntries: async () => mockEntries,
      getLastEntry: async () => mockEntries[mockEntries.length - 1],
    }
    const mockChargesRepo = {
      findPendingByUnitAndCondominium: async () => mockPendingCharges,
    }
    service = new GetAccountStatementService(mockLedgerRepo as never, mockChargesRepo as never)
  })

  it('should return entries with correct structure', async () => {
    const result = await service.execute({
      unitId, condominiumId: condominiumId,
      fromDate: '2026-01-01', toDate: '2026-02-28',
    })

    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.entries.length).toBe(3)
      expect(result.data.entries[0]!.debit).toBe('48500.00')
      expect(result.data.entries[0]!.credit).toBeNull()
      expect(result.data.entries[1]!.credit).toBe('48500.00')
      expect(result.data.entries[1]!.debit).toBeNull()
    }
  })

  it('should calculate current balance', async () => {
    const result = await service.execute({
      unitId, condominiumId: condominiumId,
      fromDate: '2026-01-01', toDate: '2026-02-28',
    })

    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.currentBalance).toBe('51200.00')
    }
  })

  it('should calculate aging buckets', async () => {
    const result = await service.execute({
      unitId, condominiumId: condominiumId,
      fromDate: '2026-01-01', toDate: '2026-02-28',
    })

    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.aging).toBeDefined()
      const totalAging =
        parseFloat(result.data.aging.current) +
        parseFloat(result.data.aging.days30) +
        parseFloat(result.data.aging.days60) +
        parseFloat(result.data.aging.days90Plus)
      expect(totalAging).toBeGreaterThanOrEqual(0)
    }
  })

  it('should calculate total debits and credits', async () => {
    const result = await service.execute({
      unitId, condominiumId: condominiumId,
      fromDate: '2026-01-01', toDate: '2026-02-28',
    })

    expect(result.success).toBe(true)
    if (result.success) {
      // 48500 + 51200 = 99700 debits
      expect(result.data.totalDebits).toBe('99700.00')
      // 48500 credits
      expect(result.data.totalCredits).toBe('48500.00')
    }
  })
})
