import type { TCharge, TPaymentAllocation, TAllocationStrategy } from '@packages/domain'
import { type TServiceResult, success, failure } from '../base.service'
import { parseAmount, toDecimal } from '@packages/utils/money'

type TChargesRepo = {
  findPendingByUnitAndCondominium: (unitId: string, condominiumId: string, orderAsc?: boolean) => Promise<TCharge[]>
  update: (id: string, data: Partial<TCharge>) => Promise<TCharge | null>
}

type TAllocationsRepo = {
  create: (data: Omit<TPaymentAllocation, 'id' | 'allocatedAt'>) => Promise<TPaymentAllocation>
}

type TReceiptsRepo = {
  update: (id: string, data: Record<string, unknown>) => Promise<unknown>
}

export interface IAllocatePaymentFIFOInput {
  paymentId: string
  unitId: string
  condominiumId: string
  amount: string
  strategy: TAllocationStrategy
  createdBy?: string | null
}

export interface IAllocatePaymentFIFOOutput {
  allocations: TPaymentAllocation[]
  remaining: string
}

export class AllocatePaymentFIFOService {
  private chargesRepo: TChargesRepo
  private allocationsRepo: TAllocationsRepo
  private receiptsRepo: TReceiptsRepo

  constructor(
    chargesRepo: TChargesRepo,
    allocationsRepo: TAllocationsRepo,
    receiptsRepo: TReceiptsRepo,
  ) {
    this.chargesRepo = chargesRepo
    this.allocationsRepo = allocationsRepo
    this.receiptsRepo = receiptsRepo
  }

  async execute(
    input: IAllocatePaymentFIFOInput
  ): Promise<TServiceResult<IAllocatePaymentFIFOOutput>> {
    let remaining = parseAmount(input.amount)

    if (remaining <= 0) {
      return failure('El monto debe ser mayor a 0', 'BAD_REQUEST')
    }

    const pendingCharges = await this.chargesRepo.findPendingByUnitAndCondominium(
      input.unitId,
      input.condominiumId,
      true // order ASC by createdAt (oldest first)
    )

    // Sort charges based on allocation strategy
    let sortedCharges = [...pendingCharges]
    if (input.strategy === 'fifo_interest_first') {
      // Interest/late_fee charges first, then by date (oldest first)
      sortedCharges.sort((a, b) => {
        const aIsInterest = a.isAutoGenerated ? -1 : 0
        const bIsInterest = b.isAutoGenerated ? -1 : 0
        if (aIsInterest !== bIsInterest) return aIsInterest - bIsInterest
        return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      })
    }
    // 'designated' strategy: the caller should pre-filter charges before calling this service
    // 'fifo': default ordering from DB (oldest first) — no change needed

    const allocations: TPaymentAllocation[] = []

    for (const charge of sortedCharges) {
      if (remaining <= 0) break

      const chargeBalance = parseAmount(charge.balance)
      if (chargeBalance <= 0) continue

      const allocatable = Math.min(remaining, chargeBalance)

      const allocation = await this.allocationsRepo.create({
        paymentId: input.paymentId,
        chargeId: charge.id,
        allocatedAmount: toDecimal(allocatable),
        reversed: false,
        reversedAt: null,
        createdBy: input.createdBy ?? null,
      })
      allocations.push(allocation)

      const newPaidAmount = parseAmount(charge.paidAmount) + allocatable
      const newBalance = parseAmount(charge.amount) - newPaidAmount
      const newStatus = newBalance <= 0.005 ? 'paid' : 'partial' // tolerance for floating point

      await this.chargesRepo.update(charge.id, {
        paidAmount: toDecimal(newPaidAmount),
        balance: toDecimal(Math.max(0, newBalance)),
        status: newStatus,
      })

      remaining -= allocatable
    }

    return success({
      allocations,
      remaining: toDecimal(Math.max(0, remaining)),
    })
  }
}
