import type { TCharge, TUnitLedgerEntry, TLedgerReferenceType } from '@packages/domain'
import { type TServiceResult, success, failure } from '../base.service'
import { parseAmount, toDecimal } from '@packages/utils/money'
import type { AppendLedgerEntryService } from './append-ledger-entry.service'

type TChargesRepo = {
  create: (data: Omit<TCharge, 'id' | 'createdAt' | 'updatedAt'>) => Promise<TCharge>
}

export interface ICreateChargeInput {
  billingChannelId: string
  chargeTypeId: string
  unitId: string
  receiptId?: string | null
  periodYear: number
  periodMonth: number
  description: string
  amount: string
  currencyId: string
  isCredit?: boolean
  isAutoGenerated?: boolean
  sourceExpenseId?: string | null
  sourceChargeId?: string | null
  entryDate: string
  referenceType?: TLedgerReferenceType
  createdBy?: string | null
}

export interface ICreateChargeOutput {
  charge: TCharge
  entry: TUnitLedgerEntry
}

export class CreateChargeWithLedgerEntryService {
  private chargesRepo: TChargesRepo
  private appendLedgerService: AppendLedgerEntryService

  constructor(chargesRepo: TChargesRepo, appendLedgerService: AppendLedgerEntryService) {
    this.chargesRepo = chargesRepo
    this.appendLedgerService = appendLedgerService
  }

  async execute(input: ICreateChargeInput): Promise<TServiceResult<ICreateChargeOutput>> {
    const amount = parseAmount(input.amount)
    if (amount <= 0) {
      return failure('El monto debe ser mayor a 0', 'BAD_REQUEST')
    }

    const isCredit = input.isCredit ?? false
    const amountStr = toDecimal(amount)

    const charge = await this.chargesRepo.create({
      billingChannelId: input.billingChannelId,
      chargeTypeId: input.chargeTypeId,
      unitId: input.unitId,
      receiptId: input.receiptId ?? null,
      periodYear: input.periodYear,
      periodMonth: input.periodMonth,
      description: input.description,
      amount: amountStr,
      isCredit,
      currencyId: input.currencyId,
      status: isCredit ? 'paid' : 'pending',
      paidAmount: '0',
      balance: isCredit ? '0' : amountStr,
      sourceExpenseId: input.sourceExpenseId ?? null,
      sourceChargeId: input.sourceChargeId ?? null,
      isAutoGenerated: input.isAutoGenerated ?? false,
      metadata: null,
      createdBy: input.createdBy ?? null,
    })

    const entryType = isCredit ? 'credit' : 'debit'
    const referenceType = input.referenceType ?? (isCredit ? 'credit_note' : 'charge')

    const entryResult = await this.appendLedgerService.execute({
      unitId: input.unitId,
      billingChannelId: input.billingChannelId,
      entryDate: input.entryDate,
      entryType,
      amount: amountStr,
      currencyId: input.currencyId,
      description: input.description,
      referenceType,
      referenceId: charge.id,
      createdBy: input.createdBy ?? null,
    })

    if (!entryResult.success) {
      return failure(entryResult.error, entryResult.code)
    }

    return success({ charge, entry: entryResult.data })
  }
}
