import type { TBillingChannel, TBillingReceipt, TChargeType, TChargeCategory } from '@packages/domain'
import { type TServiceResult, success } from '../base.service'
import { parseAmount, toDecimal } from '@packages/utils/money'
import type { CreateChargeWithLedgerEntryService } from '../billing-ledger/create-charge-with-ledger-entry.service'

type TChargeTypesRepo = {
  findAutoGenerated: (channelId: string, category: TChargeCategory) => Promise<TChargeType | null>
}

export interface IApplyLateFeeInput {
  channel: TBillingChannel
  receipt: TBillingReceipt
  unitId: string
  paymentDate: string
  createdBy?: string | null
}

export interface IApplyLateFeeOutput {
  feeAmount: string
  applied: boolean
}

export class ApplyLateFeeService {
  private chargesRepo: unknown
  private chargeTypesRepo: TChargeTypesRepo
  private createChargeService: CreateChargeWithLedgerEntryService

  constructor(
    chargesRepo: unknown,
    chargeTypesRepo: TChargeTypesRepo,
    createChargeService: CreateChargeWithLedgerEntryService,
  ) {
    this.chargesRepo = chargesRepo
    this.chargeTypesRepo = chargeTypesRepo
    this.createChargeService = createChargeService
  }

  async execute(input: IApplyLateFeeInput): Promise<TServiceResult<IApplyLateFeeOutput>> {
    const { channel, receipt, unitId, paymentDate } = input

    if (channel.latePaymentType === 'none' || !channel.latePaymentValue) {
      return success({ feeAmount: '0.00', applied: false })
    }

    if (!receipt.dueDate) {
      return success({ feeAmount: '0.00', applied: false })
    }

    const payDate = new Date(paymentDate)
    const dueDate = new Date(receipt.dueDate)
    const daysOverdue = Math.floor(
      (payDate.getTime() - dueDate.getTime()) / (1000 * 60 * 60 * 24)
    )

    if (daysOverdue <= (channel.gracePeriodDays ?? 0)) {
      return success({ feeAmount: '0.00', applied: false })
    }

    const receiptTotal = parseAmount(receipt.totalAmount)
    const feeValue = parseAmount(channel.latePaymentValue)
    let feeAmount = 0

    switch (channel.latePaymentType) {
      case 'percentage':
        feeAmount = receiptTotal * feeValue
        break
      case 'fixed':
        feeAmount = feeValue
        break
    }

    const feeStr = toDecimal(feeAmount)

    if (feeAmount > 0) {
      const lateFeeType = await this.chargeTypesRepo.findAutoGenerated(channel.id, 'late_fee')
      if (lateFeeType) {
        await this.createChargeService.execute({
          billingChannelId: channel.id,
          chargeTypeId: lateFeeType.id,
          unitId,
          periodYear: receipt.periodYear,
          periodMonth: receipt.periodMonth,
          description: `Recargo por pago tardío - ${receipt.receiptNumber}`,
          amount: feeStr,
          currencyId: channel.currencyId,
          isAutoGenerated: true,
          entryDate: paymentDate,
          referenceType: 'late_fee',
          createdBy: input.createdBy ?? null,
        })
      }
    }

    return success({ feeAmount: feeStr, applied: feeAmount > 0 })
  }
}
