import type { TBillingChannel, TBillingReceipt, TChargeType, TChargeCategory } from '@packages/domain'
import { type TServiceResult, success } from '../base.service'
import { parseAmount, toDecimal } from '@packages/utils/money'
import type { CreateChargeWithLedgerEntryService } from '../billing-ledger/create-charge-with-ledger-entry.service'

type TChargeTypesRepo = {
  findAutoGenerated: (channelId: string, category: TChargeCategory) => Promise<TChargeType | null>
}

export interface IApplyDiscountInput {
  channel: TBillingChannel
  receipt: TBillingReceipt
  unitId: string
  paymentAmount: string
  paymentDate: string
  createdBy?: string | null
}

export interface IApplyDiscountOutput {
  discountAmount: string
  applied: boolean
}

export class ApplyEarlyPaymentDiscountService {
  private chargeTypesRepo: TChargeTypesRepo
  private createChargeService: CreateChargeWithLedgerEntryService

  constructor(
    chargeTypesRepo: TChargeTypesRepo,
    createChargeService: CreateChargeWithLedgerEntryService,
  ) {
    this.chargeTypesRepo = chargeTypesRepo
    this.createChargeService = createChargeService
  }

  async execute(input: IApplyDiscountInput): Promise<TServiceResult<IApplyDiscountOutput>> {
    const { channel, receipt, unitId, paymentAmount, paymentDate } = input

    if (channel.earlyPaymentType === 'none' || !channel.earlyPaymentValue) {
      return success({ discountAmount: '0.00', applied: false })
    }

    if (!receipt.dueDate) {
      return success({ discountAmount: '0.00', applied: false })
    }

    const payDate = new Date(paymentDate)
    const dueDate = new Date(receipt.dueDate)
    const daysBeforeDue = Math.floor(
      (dueDate.getTime() - payDate.getTime()) / (1000 * 60 * 60 * 24)
    )

    if (daysBeforeDue < (channel.earlyPaymentDaysBefore ?? 0)) {
      return success({ discountAmount: '0.00', applied: false })
    }

    const amount = parseAmount(paymentAmount)
    const discountValue = parseAmount(channel.earlyPaymentValue)
    let discountAmount = 0

    switch (channel.earlyPaymentType) {
      case 'percentage':
        discountAmount = amount * discountValue
        break
      case 'fixed':
        discountAmount = discountValue
        break
    }

    const discountStr = toDecimal(discountAmount)

    if (discountAmount > 0) {
      const discountType = await this.chargeTypesRepo.findAutoGenerated(channel.id, 'discount')
      if (discountType) {
        await this.createChargeService.execute({
          billingChannelId: channel.id,
          chargeTypeId: discountType.id,
          unitId,
          periodYear: receipt.periodYear,
          periodMonth: receipt.periodMonth,
          description: `Descuento pronto pago - ${receipt.receiptNumber}`,
          amount: discountStr,
          currencyId: channel.currencyId,
          isCredit: true,
          isAutoGenerated: true,
          entryDate: paymentDate,
          referenceType: 'discount',
          createdBy: input.createdBy ?? null,
        })
      }
    }

    return success({ discountAmount: discountStr, applied: discountAmount > 0 })
  }
}
