import type { TBillingChannel, TCharge, TChargeType, TChargeCategory } from '@packages/domain'
import { type TServiceResult, success } from '../base.service'
import { parseAmount, toDecimal } from '@packages/utils/money'
import type { CreateChargeWithLedgerEntryService } from '../billing-ledger/create-charge-with-ledger-entry.service'

type TChargesRepo = {
  findPendingByUnitAndChannel: (unitId: string, channelId: string) => Promise<TCharge[]>
}

type TChargeTypesRepo = {
  findAutoGenerated: (channelId: string, category: TChargeCategory) => Promise<TChargeType | null>
}

export interface ICalculateInterestInput {
  channel: TBillingChannel
  unitId: string
  calculationDate: string
  createdBy?: string | null
}

export interface ICalculateInterestOutput {
  interestAmount: string
  overdueBalance: string
}

export class CalculateChannelInterestService {
  private chargesRepo: TChargesRepo
  private chargeTypesRepo: TChargeTypesRepo
  private createChargeService: CreateChargeWithLedgerEntryService

  constructor(
    chargesRepo: TChargesRepo,
    chargeTypesRepo: TChargeTypesRepo,
    createChargeService: CreateChargeWithLedgerEntryService,
  ) {
    this.chargesRepo = chargesRepo
    this.chargeTypesRepo = chargeTypesRepo
    this.createChargeService = createChargeService
  }

  async execute(input: ICalculateInterestInput): Promise<TServiceResult<ICalculateInterestOutput>> {
    const { channel, unitId, calculationDate } = input

    if (channel.interestType === 'none' || !channel.interestRate) {
      return success({ interestAmount: '0.00', overdueBalance: '0.00' })
    }

    // Get overdue balance (sum of pending/partial charges, excluding auto-generated interest/fees)
    const pendingCharges = await this.chargesRepo.findPendingByUnitAndChannel(unitId, channel.id)
    const overdueCharges = pendingCharges.filter(c => !c.isAutoGenerated && !c.isCredit)

    if (overdueCharges.length === 0) {
      return success({ interestAmount: '0.00', overdueBalance: '0.00' })
    }

    const overdueBalance = overdueCharges.reduce((sum, c) => sum + parseAmount(c.balance), 0)

    // Check grace period
    const oldestCharge = overdueCharges[0]
    if (!oldestCharge) return success({ interestAmount: '0.00', overdueBalance: toDecimal(overdueBalance) })
    const chargeDate = oldestCharge.createdAt instanceof Date
      ? oldestCharge.createdAt
      : new Date(oldestCharge.createdAt)
    const calcDate = new Date(calculationDate)
    const daysSinceCharge = Math.floor(
      (calcDate.getTime() - chargeDate.getTime()) / (1000 * 60 * 60 * 24)
    )

    if (daysSinceCharge <= (channel.interestGracePeriodDays ?? 0)) {
      return success({ interestAmount: '0.00', overdueBalance: toDecimal(overdueBalance) })
    }

    // Calculate interest
    const rate = parseAmount(channel.interestRate)
    let interest = 0

    switch (channel.interestType) {
      case 'simple':
        interest = overdueBalance * rate
        break
      case 'compound': {
        const months = daysSinceCharge / 30
        interest = overdueBalance * (Math.pow(1 + rate, months) - 1)
        break
      }
      case 'fixed_amount':
        interest = rate
        break
    }

    // Apply cap
    if (channel.maxInterestCapType === 'percentage_of_principal' && channel.maxInterestCapValue) {
      const cap = overdueBalance * parseAmount(channel.maxInterestCapValue)
      interest = Math.min(interest, cap)
    } else if (channel.maxInterestCapType === 'fixed' && channel.maxInterestCapValue) {
      interest = Math.min(interest, parseAmount(channel.maxInterestCapValue))
    }

    interest = Math.max(0, interest)
    const interestAmount = toDecimal(interest)

    if (interest > 0) {
      const interestChargeType = await this.chargeTypesRepo.findAutoGenerated(channel.id, 'interest')
      if (interestChargeType) {
        const now = new Date()
        await this.createChargeService.execute({
          billingChannelId: channel.id,
          chargeTypeId: interestChargeType.id,
          unitId,
          periodYear: now.getFullYear(),
          periodMonth: now.getMonth() + 1,
          description: `Interés moratorio - ${calculationDate}`,
          amount: interestAmount,
          currencyId: channel.currencyId,
          isAutoGenerated: true,
          entryDate: calculationDate,
          referenceType: 'interest',
          createdBy: input.createdBy ?? null,
        })
      }
    }

    return success({ interestAmount, overdueBalance: toDecimal(overdueBalance) })
  }
}
