import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  jsonb,
  index,
  integer,
  decimal,
} from 'drizzle-orm/pg-core'
import { condominiums } from './condominiums'
import { chargeTypes } from './charge-types'
import { units } from './units'
import { currencies } from './currencies'
import { users } from './users'
import { chargeStatusEnum, distributionMethodEnum } from '../enums'

export const charges = pgTable(
  'charges',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    condominiumId: uuid('condominium_id')
      .notNull()
      .references(() => condominiums.id, { onDelete: 'cascade' }),
    chargeTypeId: uuid('charge_type_id')
      .notNull()
      .references(() => chargeTypes.id, { onDelete: 'restrict' }),
    unitId: uuid('unit_id')
      .notNull()
      .references(() => units.id, { onDelete: 'cascade' }),
    receiptId: uuid('receipt_id'),
    // Period
    periodYear: integer('period_year').notNull(),
    periodMonth: integer('period_month').notNull(),
    description: text('description'),
    // Amounts (frozen in issuance currency)
    amount: decimal('amount', { precision: 15, scale: 2 }).notNull(),
    isCredit: boolean('is_credit').default(false),
    currencyId: uuid('currency_id')
      .notNull()
      .references(() => currencies.id, { onDelete: 'restrict' }),
    // Distribution method used when generating this charge
    distributionMethod: distributionMethodEnum('distribution_method'),
    // Payment tracking
    status: chargeStatusEnum('status').notNull().default('pending'),
    paidAmount: decimal('paid_amount', { precision: 15, scale: 2 }).default('0'),
    balance: decimal('balance', { precision: 15, scale: 2 }).notNull(),
    // References
    sourceExpenseId: uuid('source_expense_id'),
    sourceChargeId: uuid('source_charge_id'),
    sourceReceiptId: uuid('source_receipt_id'),
    // Flags
    isAutoGenerated: boolean('is_auto_generated').default(false),
    metadata: jsonb('metadata'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
  },
  table => [
    index('idx_charges_condominium').on(table.condominiumId),
    index('idx_charges_unit').on(table.unitId),
    index('idx_charges_receipt').on(table.receiptId),
    index('idx_charges_period').on(table.periodYear, table.periodMonth),
    index('idx_charges_status').on(table.status),
    index('idx_charges_charge_type').on(table.chargeTypeId),
    index('idx_charges_created_by').on(table.createdBy),
  ]
)
