import {
  pgTable,
  uuid,
  varchar,
  boolean,
  timestamp,
  integer,
  decimal,
  index,
} from 'drizzle-orm/pg-core'
import { billingChannels } from './billing-channels'
import { chargeCategoryEnum } from '../enums'

export const chargeTypes = pgTable(
  'charge_types',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    billingChannelId: uuid('billing_channel_id')
      .notNull()
      .references(() => billingChannels.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 200 }).notNull(),
    category: chargeCategoryEnum('category').notNull(),
    isAutoGenerated: boolean('is_auto_generated').default(false),
    isRecurring: boolean('is_recurring').default(true),
    defaultAmount: decimal('default_amount', { precision: 15, scale: 2 }),
    sortOrder: integer('sort_order').default(0),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
  },
  table => [
    index('idx_charge_types_channel').on(table.billingChannelId),
    index('idx_charge_types_category').on(table.category),
    index('idx_charge_types_active').on(table.isActive),
  ]
)
