import { z } from 'zod'
import { baseModelSchema } from '../../shared/base-model.schema'

export const EChargeCategories = [
  'ordinary',
  'extraordinary',
  'reserve_fund',
  'social_benefits',
  'non_common',
  'fine',
  'interest',
  'late_fee',
  'discount',
  'credit_note',
  'debit_note',
  'other',
] as const

export const chargeTypeSchema = baseModelSchema.extend({
  billingChannelId: z.uuid(),
  name: z.string().min(1).max(200),
  category: z.enum(EChargeCategories),
  isAutoGenerated: z.boolean().default(false),
  isRecurring: z.boolean().default(true),
  defaultAmount: z.string().nullable(), // decimal as string
  sortOrder: z.number().int().default(0),
  isActive: z.boolean().default(true),
})
