import { describe, it, expect } from 'bun:test'
import type { TChargeType, TChargeCategory } from '@packages/domain'

describe('ChargeTypesRepository', () => {
  const makeChargeType = (overrides: Partial<TChargeType> = {}): TChargeType => ({
    id: '550e8400-e29b-41d4-a716-446655440001',
    billingChannelId: '550e8400-e29b-41d4-a716-446655440010',
    name: 'Administración',
    category: 'ordinary',
    isAutoGenerated: false,
    isRecurring: true,
    defaultAmount: null,
    sortOrder: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  })

  describe('charge categories', () => {
    it('should support all charge categories', () => {
      const categories: TChargeCategory[] = [
        'ordinary',
        'extraordinary',
        'reserve_fund',
        'social_benefits',
        'non_common',
        'fine',
        'interest',
        'late_fee',
        'discount',
        'credit_note',
        'debit_note',
        'other',
      ]

      categories.forEach(cat => {
        const ct = makeChargeType({ category: cat })
        expect(ct.category).toBe(cat)
      })
      expect(categories.length).toBe(12)
    })

    it('should mark auto-generated types correctly', () => {
      const autoTypes: Array<{ name: string; category: TChargeCategory }> = [
        { name: 'Interés por mora', category: 'interest' },
        { name: 'Recargo por pago tardío', category: 'late_fee' },
        { name: 'Descuento por pronto pago', category: 'discount' },
      ]

      autoTypes.forEach(({ name, category }) => {
        const ct = makeChargeType({
          name,
          category,
          isAutoGenerated: true,
          isRecurring: false,
        })
        expect(ct.isAutoGenerated).toBe(true)
        expect(ct.isRecurring).toBe(false)
      })
    })

    it('reserve_fund should represent fondo de reserva (Art. 12 LPH)', () => {
      const reserveFund = makeChargeType({
        name: 'Fondo de Reserva',
        category: 'reserve_fund',
        isRecurring: true,
      })
      expect(reserveFund.category).toBe('reserve_fund')
      expect(reserveFund.isRecurring).toBe(true)
    })

    it('extraordinary should note assembly reference requirement', () => {
      const extraordinary = makeChargeType({
        name: 'Reparación ascensor',
        category: 'extraordinary',
        isRecurring: false,
      })
      expect(extraordinary.category).toBe('extraordinary')
      expect(extraordinary.isRecurring).toBe(false)
      // Assembly reference is on the billing_channel, not charge_type
    })
  })

  describe('sort order', () => {
    it('should order charge types for receipt display', () => {
      const types = [
        makeChargeType({ name: 'Administración', sortOrder: 1 }),
        makeChargeType({ name: 'Electricidad', sortOrder: 2 }),
        makeChargeType({ name: 'Vigilancia', sortOrder: 3 }),
        makeChargeType({ name: 'Fondo Reserva', sortOrder: 10, category: 'reserve_fund' }),
        makeChargeType({ name: 'Interés', sortOrder: 997, isAutoGenerated: true }),
        makeChargeType({ name: 'Recargo', sortOrder: 998, isAutoGenerated: true }),
        makeChargeType({ name: 'Descuento', sortOrder: 999, isAutoGenerated: true }),
      ]

      const sorted = [...types].sort((a, b) => a.sortOrder - b.sortOrder)
      expect(sorted[0]!.name).toBe('Administración')
      expect(sorted[sorted.length - 1]!.name).toBe('Descuento')
    })
  })
})
