import { describe, it, expect } from 'bun:test'
import type { TCharge } from '@packages/domain'

describe('ChargesRepository', () => {
  const makeCharge = (overrides: Partial<TCharge> = {}): TCharge => ({
    id: '550e8400-e29b-41d4-a716-446655440001',
    billingChannelId: '550e8400-e29b-41d4-a716-446655440010',
    chargeTypeId: '550e8400-e29b-41d4-a716-446655440020',
    unitId: '550e8400-e29b-41d4-a716-446655440030',
    receiptId: null,
    periodYear: 2026,
    periodMonth: 3,
    description: 'Administración Marzo 2026',
    amount: '4189.12',
    isCredit: false,
    currencyId: '550e8400-e29b-41d4-a716-446655440040',
    status: 'pending',
    paidAmount: '0',
    balance: '4189.12',
    sourceExpenseId: null,
    sourceChargeId: null,
    isAutoGenerated: false,
    metadata: null,
    createdBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  })

  describe('domain model', () => {
    it('should create a pending charge with correct balance', () => {
      const charge = makeCharge()
      expect(charge.status).toBe('pending')
      expect(charge.amount).toBe(charge.balance)
      expect(charge.paidAmount).toBe('0')
      expect(charge.isCredit).toBe(false)
    })

    it('should create a credit charge (nota de crédito)', () => {
      const credit = makeCharge({
        isCredit: true,
        status: 'paid',
        description: 'Nota de crédito: ajuste electricidad',
        amount: '5000.00',
        balance: '0',
      })
      expect(credit.isCredit).toBe(true)
      expect(credit.status).toBe('paid')
    })

    it('should track partial payment correctly', () => {
      const partial = makeCharge({
        status: 'partial',
        paidAmount: '2000.00',
        balance: '2189.12',
      })
      expect(partial.status).toBe('partial')
      expect(parseFloat(partial.paidAmount) + parseFloat(partial.balance)).toBeCloseTo(
        parseFloat(partial.amount),
        2
      )
    })

    it('should support auto-generated interest charges', () => {
      const interest = makeCharge({
        isAutoGenerated: true,
        description: 'Interés moratorio Marzo 2026',
        amount: '512.00',
        balance: '512.00',
        sourceChargeId: '550e8400-e29b-41d4-a716-446655440099',
      })
      expect(interest.isAutoGenerated).toBe(true)
      expect(interest.sourceChargeId).not.toBeNull()
    })

    it('should link to a receipt', () => {
      const charge = makeCharge({
        receiptId: '550e8400-e29b-41d4-a716-446655440099',
      })
      expect(charge.receiptId).not.toBeNull()
    })
  })

  describe('status transitions', () => {
    it('pending → partial when partially paid', () => {
      const charge = makeCharge()
      expect(charge.status).toBe('pending')

      const updated = makeCharge({
        ...charge,
        status: 'partial',
        paidAmount: '2000.00',
        balance: '2189.12',
      })
      expect(updated.status).toBe('partial')
    })

    it('partial → paid when fully paid', () => {
      const updated = makeCharge({
        status: 'paid',
        paidAmount: '4189.12',
        balance: '0',
      })
      expect(updated.status).toBe('paid')
      expect(updated.balance).toBe('0')
    })

    it('pending → cancelled when voided', () => {
      const cancelled = makeCharge({ status: 'cancelled', balance: '0', paidAmount: '0' })
      expect(cancelled.status).toBe('cancelled')
    })

    it('pending → exonerated', () => {
      const exonerated = makeCharge({ status: 'exonerated', balance: '0' })
      expect(exonerated.status).toBe('exonerated')
    })
  })
})
