import { z } from 'zod'
import { baseModelSchema } from '../../shared/base-model.schema'

export const EChargeStatuses = [
  'pending',
  'paid',
  'partial',
  'cancelled',
  'exonerated',
] as const

export const chargeSchema = baseModelSchema.extend({
  billingChannelId: z.uuid(),
  chargeTypeId: z.uuid(),
  unitId: z.uuid(),
  receiptId: z.uuid().nullable(),
  periodYear: z.number().int().min(2000).max(2100),
  periodMonth: z.number().int().min(1).max(12),
  description: z.string().nullable(),
  amount: z.string(), // decimal as string
  isCredit: z.boolean().default(false),
  currencyId: z.uuid(),
  status: z.enum(EChargeStatuses).default('pending'),
  paidAmount: z.string().default('0'),
  balance: z.string(),
  sourceExpenseId: z.uuid().nullable(),
  sourceChargeId: z.uuid().nullable(),
  isAutoGenerated: z.boolean().default(false),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  createdBy: z.uuid().nullable(),
})
