import type PgBoss from 'pg-boss'
import { DatabaseService } from '@database/service'
import {
  BillingChannelsRepository,
  ChargeTypesRepository,
  BillingReceiptsRepository,
  ChargesRepository,
  UnitLedgerRepository,
  UnitsRepository,
  CondominiumsRepository,
  EventLogsRepository,
} from '@database/repositories'
import { EventLogger } from '@packages/services'
import { AppendLedgerEntryService } from '@api/services/billing-ledger/append-ledger-entry.service'
import { GenerateChannelPeriodService } from '@api/services/billing-generation/generate-channel-period.service'
import logger from '@packages/logger'
import { notifySuperadminsOnError } from '@worker/libs/notify-superadmins-on-error'
import type { IAutoGenerateJobData } from '@worker/boss/queues'

/**
 * Billing Auto-Generation Processor (Fase 4.7)
 *
 * For channels with generationStrategy='auto' and charge_types with defaultAmount:
 * auto-generates charges + receipts for the current period.
 *
 * NOTE: Only works for channels with fixed amounts (defaultAmount on charge_types).
 * Variable-amount channels require manual generation by admin.
 */
export async function processBillingAutoGeneration(
  job: PgBoss.Job<IAutoGenerateJobData>
): Promise<void> {
  const start = Date.now()
  logger.info({ jobId: job.id }, '[BillingAutoGen] Starting')

  const db = DatabaseService.getInstance().getDb()
  const eventLogger = new EventLogger(new EventLogsRepository(db), {
    source: 'worker',
    module: 'billing-auto-generation.processor',
  })

  try {
    const channelsRepo = new BillingChannelsRepository(db)
    const chargeTypesRepo = new ChargeTypesRepository(db)
    const receiptsRepo = new BillingReceiptsRepository(db)
    const chargesRepo = new ChargesRepository(db)
    const ledgerRepo = new UnitLedgerRepository(db)
    const unitsRepo = new UnitsRepository(db)
    const condominiumsRepo = new CondominiumsRepository(db)

    const appendLedgerService = new AppendLedgerEntryService(ledgerRepo)
    const generateService = new GenerateChannelPeriodService(
      channelsRepo, unitsRepo as any, chargeTypesRepo,
      receiptsRepo, chargesRepo, ledgerRepo,
      appendLedgerService, condominiumsRepo as any,
    )

    // Get all active channels with auto generation
    const allChannels = await channelsRepo.listAll()
    const autoChannels = allChannels.filter(
      ch => ch.generationStrategy === 'auto' && ch.isActive
    )

    if (autoChannels.length === 0) {
      logger.info('[BillingAutoGen] No auto-strategy channels found')
      return
    }

    const now = new Date()
    const currentYear = now.getUTCFullYear()
    const currentMonth = now.getUTCMonth() + 1

    let totalGenerated = 0
    let totalFailed = 0

    for (const channel of autoChannels) {
      try {
        // Check if today is the generation day
        const today = now.getUTCDate()
        if (channel.generationDay && today !== channel.generationDay) {
          continue // Not the right day
        }

        // Get charge types with default amounts
        const chargeTypes = await chargeTypesRepo.listByChannel(channel.id)
        const withDefaults = chargeTypes.filter(
          ct => !ct.isAutoGenerated && ct.defaultAmount && ct.isActive
        )

        if (withDefaults.length === 0) {
          logger.warn(
            { channelId: channel.id, channelName: channel.name },
            '[BillingAutoGen] No charge types with defaultAmount — skipping (use manual generation)'
          )
          continue
        }

        const chargeAmounts = withDefaults.map(ct => ({
          chargeTypeId: ct.id,
          amount: ct.defaultAmount!,
          description: `${ct.name} - auto`,
        }))

        const result = await generateService.execute({
          channelId: channel.id,
          periodYear: currentYear,
          periodMonth: currentMonth,
          chargeAmounts,
        })

        if (result.success) {
          totalGenerated += result.data.totalGenerated
          logger.info(
            { channelId: channel.id, receipts: result.data.totalGenerated },
            '[BillingAutoGen] Channel processed'
          )
        } else {
          // CONFLICT = already generated, not an error
          if (result.code !== 'CONFLICT') {
            totalFailed++
            logger.warn({ channelId: channel.id, error: result.error }, '[BillingAutoGen] Failed')
          }
        }
      } catch (error) {
        totalFailed++
        logger.error({ channelId: channel.id, error }, '[BillingAutoGen] Error')
      }
    }

    const elapsed = ((Date.now() - start) / 1000).toFixed(1)
    logger.info({ elapsed, totalGenerated, totalFailed }, '[BillingAutoGen] Completed')

    eventLogger.info({
      category: 'worker',
      event: 'worker.billing_auto_generation.completed',
      action: 'billing_auto_generate',
      message: `Generated ${totalGenerated} receipts across ${autoChannels.length} channels`,
      metadata: { totalGenerated, totalFailed, channelsProcessed: autoChannels.length },
      durationMs: Date.now() - start,
    })
  } catch (error) {
    logger.error({ error }, '[BillingAutoGen] Fatal error')
    await notifySuperadminsOnError({ jobId: job.id, processor: 'billing-auto-generation', error, elapsedSeconds: ((Date.now() - start) / 1000).toFixed(1) })
    throw error
  }
}
