'use client'

import { useRouter } from 'next/navigation'
import { Settings, Calendar, ArrowRight } from 'lucide-react'
import { useBillingChannelDetail, useBillingChannelChargeTypes } from '@packages/http-client'

import { Typography } from '@/ui/components/typography'
import { Button } from '@/ui/components/button'
import { Chip } from '@/ui/components/chip'
import { Spinner } from '@/ui/components/spinner'
import { Card } from '@/ui/components/card'

const CATEGORY_LABELS: Record<string, string> = {
  ordinary: 'Gasto Comun',
  extraordinary: 'Extraordinario',
  reserve_fund: 'Fondo Reserva',
  social_benefits: 'Prest. Sociales',
  non_common: 'No Comun',
  fine: 'Multa',
  interest: 'Interes',
  late_fee: 'Recargo',
  discount: 'Descuento',
  credit_note: 'Nota Credito',
  debit_note: 'Nota Debito',
  other: 'Otro',
}

interface IBillingChannelDetailClientProps {
  channelId: string
}

export function BillingChannelDetailClient({ channelId }: IBillingChannelDetailClientProps) {
  const router = useRouter()
  const { data: channelData, isLoading } = useBillingChannelDetail(channelId)
  const { data: chargeTypesData } = useBillingChannelChargeTypes(channelId)

  const channel = channelData?.data
  const chargeTypes = chargeTypesData?.data ?? []

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Spinner />
      </div>
    )
  }

  if (!channel) {
    return <Typography color="muted">Canal no encontrado</Typography>
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Typography variant="h2">{channel.name}</Typography>
          <Typography className="mt-1" color="muted">
            {channel.channelType === 'receipt' ? 'Canal tipo Recibo' : 'Canal Independiente'}
            {' — '}
            {channel.isActive ? 'Activo' : 'Inactivo'}
          </Typography>
        </div>
        {channel.channelType === 'receipt' && (
          <Button
            color="primary"
            startContent={<Calendar className="h-4 w-4" />}
            onPress={() => router.push(`/dashboard/billing-channels/${channelId}/generate`)}
          >
            Generar Periodo
          </Button>
        )}
      </div>

      {/* Config summary cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="p-4">
          <Typography variant="caption" color="muted">Frecuencia</Typography>
          <Typography className="mt-1 font-semibold capitalize">{channel.frequency.replace('_', ' ')}</Typography>
        </Card>
        <Card className="p-4">
          <Typography variant="caption" color="muted">Distribucion</Typography>
          <Typography className="mt-1 font-semibold capitalize">{channel.distributionMethod.replace(/_/g, ' ')}</Typography>
        </Card>
        <Card className="p-4">
          <Typography variant="caption" color="muted">Dia de Generacion</Typography>
          <Typography className="mt-1 font-semibold">{channel.generationDay}</Typography>
        </Card>
        <Card className="p-4">
          <Typography variant="caption" color="muted">Dia de Vencimiento</Typography>
          <Typography className="mt-1 font-semibold">{channel.dueDay}</Typography>
        </Card>
      </div>

      {/* Charge types */}
      <div>
        <Typography variant="h3" className="mb-3">Tipos de Cargo</Typography>
        <div className="space-y-2">
          {chargeTypes.map(ct => (
            <div
              key={ct.id}
              className="flex items-center justify-between rounded-lg border border-default-200 p-3"
            >
              <div className="flex items-center gap-3">
                <Typography className="font-medium">{ct.name}</Typography>
                <Chip size="sm" color={ct.isAutoGenerated ? 'warning' : 'default'}>
                  {CATEGORY_LABELS[ct.category] ?? ct.category}
                </Chip>
                {ct.isAutoGenerated && (
                  <Chip size="sm" color="warning" variant="flat">Auto</Chip>
                )}
              </div>
              {ct.defaultAmount && (
                <Typography color="muted">{ct.defaultAmount}</Typography>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Interest/fee config */}
      {(channel.interestType !== 'none' || channel.latePaymentType !== 'none' || channel.earlyPaymentType !== 'none') && (
        <div>
          <Typography variant="h3" className="mb-3">Reglas de Cobro</Typography>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            {channel.interestType !== 'none' && (
              <Card className="p-4">
                <Typography variant="caption" color="muted">Interes por Mora</Typography>
                <Typography className="mt-1 font-semibold">
                  {channel.interestRate ? `${(parseFloat(channel.interestRate) * 100).toFixed(1)}%` : '-'} {channel.interestType}
                </Typography>
              </Card>
            )}
            {channel.latePaymentType !== 'none' && (
              <Card className="p-4">
                <Typography variant="caption" color="muted">Recargo Pago Tardio</Typography>
                <Typography className="mt-1 font-semibold">
                  {channel.latePaymentValue ?? '-'} ({channel.latePaymentType})
                </Typography>
              </Card>
            )}
            {channel.earlyPaymentType !== 'none' && (
              <Card className="p-4">
                <Typography variant="caption" color="muted">Descuento Pronto Pago</Typography>
                <Typography className="mt-1 font-semibold">
                  {channel.earlyPaymentValue ?? '-'} ({channel.earlyPaymentType})
                </Typography>
              </Card>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
