import type { TPayment, TPaymentCreate } from '@packages/domain'
import type {
  PaymentsRepository,
  UsersRepository,
  UnitsRepository,
  CurrenciesRepository,
  PaymentGatewaysRepository,
  GatewayTransactionsRepository,
} from '@database/repositories'
import type { PaymentGatewayManager } from '../payment-gateways/gateway-manager'
import { type TServiceResult, success, failure } from '../base.service'
import { parseAmount } from '@packages/utils/money'
import logger from '@packages/logger'

export interface ICreatePaymentInput {
  userId: string
  unitId: string
  amount: string
  currencyId: string
  paymentMethod: TPayment['paymentMethod']
  paymentGatewayId?: string | null
  paymentDetails?: Record<string, unknown> | null
  paymentDate: string
  receiptUrl?: string | null
  receiptNumber?: string | null
  notes?: string | null
  registeredByUserId: string
}

export interface ICreatePaymentOutput {
  payment: TPayment
  message: string
  /** Redirect URL for gateway-based payments (e.g. Stripe Checkout) */
  redirectUrl?: string
  /** Gateway transaction ID for tracking */
  gatewayTransactionId?: string
}

/**
 * Service for creating a new payment.
 * Creates payment with 'pending' status for gateway/automatic processing,
 * or 'pending_verification' for manual payment methods.
 */
export class CreatePaymentService {
  constructor(
    private readonly paymentsRepository: PaymentsRepository,
    private readonly usersRepository: UsersRepository,
    private readonly unitsRepository: UnitsRepository,
    private readonly currenciesRepository: CurrenciesRepository,
    private readonly paymentGatewaysRepository?: PaymentGatewaysRepository,
    private readonly gatewayTransactionsRepository?: GatewayTransactionsRepository,
    private readonly gatewayManager?: PaymentGatewayManager
  ) {}

  async execute(input: ICreatePaymentInput): Promise<TServiceResult<ICreatePaymentOutput>> {
    // 1. Validate user exists
    const user = await this.usersRepository.getById(input.userId)
    if (!user) {
      return failure('User not found', 'NOT_FOUND')
    }

    // 2. Validate unit exists
    const unit = await this.unitsRepository.getById(input.unitId)
    if (!unit) {
      return failure('Unit not found', 'NOT_FOUND')
    }

    // 3. Validate currency exists and is active
    const currency = await this.currenciesRepository.getById(input.currencyId)
    if (!currency) {
      return failure('Currency not found', 'NOT_FOUND')
    }

    if (!currency.isActive) {
      return failure('Currency is not active', 'BAD_REQUEST')
    }

    // 4. Duplicate reference detection
    if (input.receiptNumber) {
      const existing = await this.paymentsRepository.getByReceiptNumber(input.receiptNumber)
      if (existing.length > 0) {
        return failure(
          `Ya existe un pago registrado con la referencia "${input.receiptNumber}". ` +
            `Si este es un pago diferente, por favor verifica el número de referencia.`,
          'CONFLICT'
        )
      }
    }

    // 5. Validate amount is positive
    const amount = parseAmount(input.amount)
    if (amount <= 0) {
      return failure('Amount must be a positive number', 'BAD_REQUEST')
    }

    // 6. Validate gateway payment method requires a paymentGatewayId
    if (input.paymentMethod === 'gateway' && !input.paymentGatewayId) {
      return failure('Payment method "gateway" requires a paymentGatewayId', 'BAD_REQUEST')
    }

    // 8. Determine initial status based on payment method
    // Gateway payments start as 'pending' for automatic processing
    // Manual methods (transfer, cash, card, mobile_payment) start as 'pending_verification'
    const status: TPayment['status'] =
      input.paymentMethod === 'gateway' ? 'pending' : 'pending_verification'

    // 9. Create payment
    const paymentData: TPaymentCreate = {
      paymentNumber: null, // Will be generated by DB trigger or service
      userId: input.userId,
      unitId: input.unitId,
      amount: input.amount,
      currencyId: input.currencyId,
      paidAmount: null,
      paidCurrencyId: null,
      exchangeRate: null,
      paymentMethod: input.paymentMethod,
      paymentGatewayId: input.paymentGatewayId ?? null,
      paymentDetails: input.paymentDetails ?? null,
      paymentDate: input.paymentDate,
      status,
      receiptUrl: input.receiptUrl ?? null,
      receiptNumber: input.receiptNumber ?? null,
      notes: input.notes ?? null,
      metadata: null,
      registeredBy: input.registeredByUserId,
    }

    const payment = await this.paymentsRepository.create(paymentData)

    let message =
      status === 'pending'
        ? 'Payment created and pending automatic processing'
        : 'Payment created and pending manual verification'

    let redirectUrl: string | undefined
    let gatewayTransactionId: string | undefined

    // 10. If gateway payment, initiate through the gateway adapter
    if (
      input.paymentMethod === 'gateway' &&
      input.paymentGatewayId &&
      this.paymentGatewaysRepository &&
      this.gatewayTransactionsRepository &&
      this.gatewayManager
    ) {
      try {
        const gateway = await this.paymentGatewaysRepository.getById(input.paymentGatewayId)

        if (gateway && this.gatewayManager.hasAdapter(gateway.gatewayType)) {
          const adapter = this.gatewayManager.getAdapter(gateway.gatewayType)
          const config = (gateway.configuration as Record<string, unknown>) ?? {}

          // Validate gateway configuration before calling external API
          const configValidation = adapter.validateConfiguration(config)
          if (!configValidation.valid) {
            logger.warn(
              {
                paymentId: payment.id,
                gatewayType: gateway.gatewayType,
                missingFields: configValidation.missingFields,
              },
              '[CreatePayment] Gateway configuration incomplete — skipping initiation'
            )
          } else {
            const gatewayResponse = await adapter.initiatePayment(
              {
                paymentId: payment.id,
                amount: input.amount,
                currencyCode: currency.code ?? input.currencyId,
                metadata: { userId: input.userId, unitId: input.unitId },
              },
              config
            )

            // Create gateway transaction record for audit
            const gatewayTx = await this.gatewayTransactionsRepository.create({
              paymentId: payment.id,
              gatewayType: gateway.gatewayType,
              externalTransactionId: gatewayResponse.externalTransactionId,
              externalReference: gatewayResponse.externalReference,
              requestPayload: { amount: input.amount, currencyId: input.currencyId },
              responsePayload: gatewayResponse.rawResponse,
              status: gatewayResponse.status,
              attempts: 0,
              maxAttempts: 10,
              lastAttemptAt: null,
              verifiedAt: null,
              errorMessage: null,
            })

            redirectUrl = gatewayResponse.redirectUrl
            gatewayTransactionId = gatewayTx.id
            message = 'Payment created and gateway initiation successful'
          }
        }
      } catch (error) {
        logger.error({ error, paymentId: payment.id }, '[CreatePayment] Gateway initiation failed')
        // Payment is still created — gateway initiation failure is non-blocking
      }
    }

    return success({
      payment,
      message,
      redirectUrl,
      gatewayTransactionId,
    })
  }
}
