import { eq, and, asc, inArray, sql } from 'drizzle-orm'
import type { TCharge, TChargeStatus } from '@packages/domain'
import { charges } from '../drizzle/schema'
import type { TDrizzleClient } from './interfaces'
import { BaseRepository } from './base'

type TChargeRecord = typeof charges.$inferSelect
type TChargeCreate = Omit<TCharge, 'id' | 'createdAt' | 'updatedAt'>
type TChargeUpdate = Partial<TChargeCreate>

export class ChargesRepository extends BaseRepository<
  typeof charges,
  TCharge,
  TChargeCreate,
  TChargeUpdate
> {
  constructor(db: TDrizzleClient) {
    super(db, charges)
  }

  protected mapToEntity(record: unknown): TCharge {
    const r = record as TChargeRecord
    return {
      id: r.id,
      condominiumId: r.condominiumId,
      chargeTypeId: r.chargeTypeId,
      unitId: r.unitId,
      receiptId: r.receiptId,
      periodYear: r.periodYear,
      periodMonth: r.periodMonth,
      description: r.description,
      amount: r.amount,
      isCredit: r.isCredit ?? false,
      currencyId: r.currencyId,
      distributionMethod: r.distributionMethod,
      status: r.status,
      paidAmount: r.paidAmount ?? '0',
      balance: r.balance,
      sourceExpenseId: r.sourceExpenseId,
      sourceChargeId: r.sourceChargeId,
      sourceReceiptId: r.sourceReceiptId,
      isAutoGenerated: r.isAutoGenerated ?? false,
      metadata: r.metadata as Record<string, unknown> | null,
      createdBy: r.createdBy,
      createdAt: r.createdAt ?? new Date(),
      updatedAt: r.updatedAt ?? new Date(),
    }
  }

  async findByReceipt(receiptId: string): Promise<TCharge[]> {
    const results = await this.db
      .select()
      .from(charges)
      .where(eq(charges.receiptId, receiptId))

    return results.map(r => this.mapToEntity(r))
  }

  async findPendingByUnitAndCondominium(
    unitId: string,
    condominiumId: string,
    orderAsc = true
  ): Promise<TCharge[]> {
    const results = await this.db
      .select()
      .from(charges)
      .where(
        and(
          eq(charges.unitId, unitId),
          eq(charges.condominiumId, condominiumId),
          inArray(charges.status, ['pending', 'partial'])
        )
      )
      .orderBy(orderAsc ? asc(charges.createdAt) : sql`${charges.createdAt} DESC`)

    return results.map(r => this.mapToEntity(r))
  }

  async findByUnitAndPeriod(
    unitId: string,
    condominiumId: string,
    periodYear: number,
    periodMonth: number
  ): Promise<TCharge[]> {
    const results = await this.db
      .select()
      .from(charges)
      .where(
        and(
          eq(charges.unitId, unitId),
          eq(charges.condominiumId, condominiumId),
          eq(charges.periodYear, periodYear),
          eq(charges.periodMonth, periodMonth)
        )
      )

    return results.map(r => this.mapToEntity(r))
  }
}
