import { eq, and } from 'drizzle-orm'
import type { TChargeType, TChargeCategory } from '@packages/domain'
import { chargeTypes } from '../drizzle/schema'
import type { TDrizzleClient } from './interfaces'
import { BaseRepository } from './base'

type TChargeTypeRecord = typeof chargeTypes.$inferSelect
type TChargeTypeCreate = Omit<TChargeType, 'id' | 'createdAt' | 'updatedAt'>
type TChargeTypeUpdate = Partial<TChargeTypeCreate>

export class ChargeTypesRepository extends BaseRepository<
  typeof chargeTypes,
  TChargeType,
  TChargeTypeCreate,
  TChargeTypeUpdate
> {
  constructor(db: TDrizzleClient) {
    super(db, chargeTypes)
  }

  protected mapToEntity(record: unknown): TChargeType {
    const r = record as TChargeTypeRecord
    return {
      id: r.id,
      billingChannelId: r.billingChannelId,
      name: r.name,
      category: r.category,
      isAutoGenerated: r.isAutoGenerated ?? false,
      isRecurring: r.isRecurring ?? true,
      defaultAmount: r.defaultAmount,
      sortOrder: r.sortOrder ?? 0,
      isActive: r.isActive ?? true,
      createdAt: r.createdAt ?? new Date(),
      updatedAt: r.updatedAt ?? new Date(),
    }
  }

  async listByChannel(channelId: string, onlyActive = true): Promise<TChargeType[]> {
    const conditions = [eq(chargeTypes.billingChannelId, channelId)]
    if (onlyActive) conditions.push(eq(chargeTypes.isActive, true))

    const results = await this.db
      .select()
      .from(chargeTypes)
      .where(and(...conditions))

    return results.map(r => this.mapToEntity(r))
  }

  async findAutoGenerated(channelId: string, category: TChargeCategory): Promise<TChargeType | null> {
    const results = await this.db
      .select()
      .from(chargeTypes)
      .where(
        and(
          eq(chargeTypes.billingChannelId, channelId),
          eq(chargeTypes.category, category),
          eq(chargeTypes.isAutoGenerated, true)
        )
      )
      .limit(1)

    return results[0] ? this.mapToEntity(results[0]) : null
  }
}
