import { describe, it, expect, beforeEach } from 'bun:test'
import type { TBillingChannel, TChargeType, TBillingReceipt, TCharge, TUnitLedgerEntry } from '@packages/domain'
import { GenerateChannelPeriodService } from '@src/services/billing-generation/generate-channel-period.service'

// ─── Constants ───
const channelId = 'channel-001'
const condoId = 'condo-001'
const currencyId = 'currency-001'

const units = [
  { id: 'unit-1', unitNumber: 'A-1-1', aliquotPercentage: '2.15', buildingId: 'b1', isActive: true },
  { id: 'unit-2', unitNumber: 'B-2-4', aliquotPercentage: '1.52', buildingId: 'b1', isActive: true },
  { id: 'unit-3', unitNumber: 'C-3-1', aliquotPercentage: '1.80', buildingId: 'b1', isActive: true },
]

const chargeTypes: TChargeType[] = [
  { id: 'ct-1', billingChannelId: channelId, name: 'Administración', category: 'ordinary', isAutoGenerated: false, isRecurring: true, defaultAmount: null, sortOrder: 1, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'ct-2', billingChannelId: channelId, name: 'Electricidad', category: 'ordinary', isAutoGenerated: false, isRecurring: true, defaultAmount: null, sortOrder: 2, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'ct-rf', billingChannelId: channelId, name: 'Fondo Reserva', category: 'reserve_fund', isAutoGenerated: false, isRecurring: true, defaultAmount: null, sortOrder: 10, isActive: true, createdAt: new Date(), updatedAt: new Date() },
]

function makeChannel(overrides: Partial<TBillingChannel> = {}): TBillingChannel {
  return {
    id: channelId, condominiumId: condoId, buildingId: null,
    name: 'Recibo Condominio', channelType: 'receipt', currencyId,
    managedBy: null, distributionMethod: 'by_aliquot',
    frequency: 'monthly', generationStrategy: 'manual',
    generationDay: 5, dueDay: 28,
    latePaymentType: 'none', latePaymentValue: null, gracePeriodDays: 0,
    earlyPaymentType: 'none', earlyPaymentValue: null, earlyPaymentDaysBefore: 0,
    interestType: 'none', interestRate: null,
    interestCalculationPeriod: null, interestGracePeriodDays: 0,
    maxInterestCapType: 'none', maxInterestCapValue: null,
    allocationStrategy: 'fifo', assemblyReference: null,
    isActive: true, effectiveFrom: '2026-01-01', effectiveUntil: null,
    receiptNumberFormat: null, metadata: null, createdBy: null,
    createdAt: new Date(), updatedAt: new Date(),
    ...overrides,
  }
}

// ─── Mocks ───
let createdCharges: any[]
let createdReceipts: any[]
let createdEntries: any[]
let receiptCounter: number

describe('GenerateChannelPeriodService', () => {
  let service: GenerateChannelPeriodService

  beforeEach(() => {
    createdCharges = []
    createdReceipts = []
    createdEntries = []
    receiptCounter = 0

    const mockBillingChannelsRepo = {
      getById: async () => makeChannel(),
    }

    const mockUnitsRepo = {
      findByCondominium: async () => units,
      findByBuilding: async () => units,
    }

    const mockChargeTypesRepo = {
      listByChannel: async () => chargeTypes,
    }

    const mockReceiptsRepo = {
      findActiveByChannelAndPeriod: async () => [],
      create: async (data: any) => {
        const receipt = {
          id: `receipt-${++receiptCounter}`,
          ...data,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
        createdReceipts.push(receipt)
        return receipt
      },
    }

    const mockChargesRepo = {
      create: async (data: any) => {
        const charge = {
          id: `charge-${createdCharges.length + 1}`,
          ...data,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
        createdCharges.push(charge)
        return charge
      },
      update: async (id: string, data: any) => {
        const idx = createdCharges.findIndex((c: any) => c.id === id)
        if (idx >= 0) createdCharges[idx] = { ...createdCharges[idx], ...data }
        return createdCharges[idx]
      },
    }

    const mockLedgerRepo = {
      getLastEntry: async () => null,
    }

    const mockAppendLedgerService = {
      execute: async (input: any) => {
        const entry = { id: `entry-${createdEntries.length + 1}`, ...input, createdAt: new Date() }
        createdEntries.push(entry)
        return { success: true, data: entry }
      },
    }

    const mockCondominiumsRepo = {
      getById: async () => ({ id: condoId, code: 'LV', receiptNumberFormat: null }),
    }

    service = new GenerateChannelPeriodService(
      mockBillingChannelsRepo as never,
      mockUnitsRepo as never,
      mockChargeTypesRepo as never,
      mockReceiptsRepo as never,
      mockChargesRepo as never,
      mockLedgerRepo as never,
      mockAppendLedgerService as never,
      mockCondominiumsRepo as never,
    )
  })

  describe('basic generation', () => {
    it('should generate receipts for all units', async () => {
      const result = await service.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [
          { chargeTypeId: 'ct-1', amount: '275600.00', description: 'Administración Marzo' },
          { chargeTypeId: 'ct-2', amount: '122515.00', description: 'Electricidad Marzo' },
          { chargeTypeId: 'ct-rf', amount: '28530.00', description: 'Fondo Reserva Marzo' },
        ],
        createdBy: 'admin-001',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.receipts.length).toBe(3) // 3 units
        expect(createdReceipts.length).toBe(3)
      }
    })

    it('should create charges per unit distributed by aliquot', async () => {
      const result = await service.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [
          { chargeTypeId: 'ct-1', amount: '100000.00' },
        ],
        createdBy: 'admin-001',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        // unit-1: 2.15% of 100000 = 2150
        // unit-2: 1.52% of 100000 = 1520
        // unit-3: 1.80% of 100000 = 1800
        const unit1Charges = createdCharges.filter((c: any) => c.unitId === 'unit-1')
        const unit2Charges = createdCharges.filter((c: any) => c.unitId === 'unit-2')
        const unit3Charges = createdCharges.filter((c: any) => c.unitId === 'unit-3')

        expect(unit1Charges.length).toBe(1)
        expect(parseFloat(unit1Charges[0].amount)).toBeCloseTo(2150, 0)
        expect(parseFloat(unit2Charges[0].amount)).toBeCloseTo(1520, 0)
        expect(parseFloat(unit3Charges[0].amount)).toBeCloseTo(1800, 0)
      }
    })

    it('should create ledger entries for each charge', async () => {
      await service.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [
          { chargeTypeId: 'ct-1', amount: '100000.00' },
        ],
        createdBy: 'admin-001',
      })

      // 3 units × 1 charge = 3 entries
      expect(createdEntries.length).toBe(3)
      expect(createdEntries.every((e: any) => e.entryType === 'debit')).toBe(true)
    })

    it('should assign sequential receipt numbers', async () => {
      const result = await service.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [
          { chargeTypeId: 'ct-1', amount: '100000.00' },
        ],
        createdBy: 'admin-001',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        const numbers = result.data.receipts.map((r: any) => r.receiptNumber)
        // All should be unique
        expect(new Set(numbers).size).toBe(numbers.length)
        // All should have a format
        numbers.forEach((n: string) => expect(n.length).toBeGreaterThan(0))
      }
    })
  })

  describe('receipt totals', () => {
    it('should calculate subtotal and totalAmount correctly', async () => {
      const result = await service.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [
          { chargeTypeId: 'ct-1', amount: '100000.00' }, // ordinary
          { chargeTypeId: 'ct-2', amount: '50000.00' },  // ordinary
          { chargeTypeId: 'ct-rf', amount: '15000.00' }, // reserve_fund
        ],
        createdBy: 'admin-001',
      })

      expect(result.success).toBe(true)
      if (result.success) {
        const receipt = result.data.receipts[0]!
        const subtotal = parseFloat(receipt.subtotal)
        const reserve = parseFloat(receipt.reserveFundAmount)
        const total = parseFloat(receipt.totalAmount)
        // Total should be subtotal + reserve + previousBalance
        expect(total).toBeCloseTo(subtotal + reserve, 1)
      }
    })
  })

  describe('conflict detection', () => {
    it('should fail if receipts already exist for the period', async () => {
      const mockReceiptsWithExisting = {
        findActiveByChannelAndPeriod: async () => [{ id: 'existing-receipt' }],
        create: async () => ({}),
      }

      const svc = new GenerateChannelPeriodService(
        { getById: async () => makeChannel() } as never,
        { findByCondominium: async () => units } as never,
        { listByChannel: async () => chargeTypes } as never,
        mockReceiptsWithExisting as never,
        {} as never,
        {} as never,
        {} as never,
        {} as never,
      )

      const result = await svc.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [{ chargeTypeId: 'ct-1', amount: '100000.00' }],
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.code).toBe('CONFLICT')
      }
    })
  })

  describe('inactive channel', () => {
    it('should fail if channel is inactive', async () => {
      const svc = new GenerateChannelPeriodService(
        { getById: async () => makeChannel({ isActive: false }) } as never,
        {} as never, {} as never, {} as never,
        {} as never, {} as never, {} as never, {} as never,
      )

      const result = await svc.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [{ chargeTypeId: 'ct-1', amount: '100000.00' }],
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.code).toBe('BAD_REQUEST')
      }
    })
  })

  describe('no units', () => {
    it('should fail if no active units found', async () => {
      const svc = new GenerateChannelPeriodService(
        { getById: async () => makeChannel() } as never,
        { findByCondominium: async () => [] } as never,
        { listByChannel: async () => chargeTypes } as never,
        { findActiveByChannelAndPeriod: async () => [] } as never,
        {} as never, {} as never, {} as never, {} as never,
      )

      const result = await svc.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [{ chargeTypeId: 'ct-1', amount: '100000.00' }],
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.code).toBe('BAD_REQUEST')
      }
    })
  })

  describe('previous balance', () => {
    it('should include previous balance in receipt total', async () => {
      const mockLedgerWithBalance = {
        getLastEntry: async () => ({ runningBalance: '10000.00' }),
      }

      const svc = new GenerateChannelPeriodService(
        { getById: async () => makeChannel() } as never,
        { findByCondominium: async () => [units[0]] } as never, // single unit
        { listByChannel: async () => [chargeTypes[0]] } as never, // single charge type
        {
          findActiveByChannelAndPeriod: async () => [],
          create: async (data: any) => {
            const r = { id: 'r-1', ...data, createdAt: new Date(), updatedAt: new Date() }
            createdReceipts.push(r)
            return r
          },
        } as never,
        {
          create: async (data: any) => {
            const c = { id: `c-${createdCharges.length + 1}`, ...data, createdAt: new Date(), updatedAt: new Date() }
            createdCharges.push(c)
            return c
          },
          update: async () => null,
        } as never,
        mockLedgerWithBalance as never,
        {
          execute: async (input: any) => ({ success: true, data: { id: 'e-1', ...input } }),
        } as never,
        { getById: async () => ({ id: condoId, code: 'LV', receiptNumberFormat: null }) } as never,
      )

      const result = await svc.execute({
        channelId,
        periodYear: 2026,
        periodMonth: 3,
        chargeAmounts: [{ chargeTypeId: 'ct-1', amount: '100000.00' }],
      })

      expect(result.success).toBe(true)
      if (result.success) {
        const receipt = result.data.receipts[0]!
        expect(receipt.previousBalance).toBe('10000.00')
        // Total = subtotal + previousBalance
        const total = parseFloat(receipt.totalAmount)
        const subtotal = parseFloat(receipt.subtotal)
        expect(total).toBeCloseTo(subtotal + 10000, 1)
      }
    })
  })
})
