// Config
export { getEnvConfig, setEnvConfig, resetEnvConfig } from './config/index'
export type { EnvConfig } from './config/index'

// Client
export {
  createHttpClient,
  getHttpClient,
  setHttpClient,
  setGlobalLocale,
  setGlobalAuthToken,
  setGlobalCondominiumId,
  setGlobalManagementCompanyId,
} from './client/index'
export type { HttpClient, HttpClientConfig } from './client/index'

// Hooks
export {
  createQueryClient,
  getQueryClient,
  setQueryClient,
  QueryProvider,
  useApiQuery,
  useApiMutation,
  useHealthCheck,
  useCurrentUser,
  useUserByFirebaseUid,
  getUserByEmail,
  useUserCondominiums,
  useCompanyCondominiums,
  useCompanyCondominiumsPaginated,
  getCompanyCondominiums,
  getCompanyCondominiumsPaginated,
  companyCondominiumsKeys,
  useCondominiums,
  useCondominiumsPaginated,
  usePlatformCondominiumsPaginated,
  useCreateCondominium,
  useUpdateCondominium,
  useGenerateCondominiumCode,
  condominiumsKeys,
  getAllCondominiums,
  getCondominiumsPaginated,
  getPlatformCondominiumsPaginated,
  createCondominium,
  updateCondominium,
  generateCondominiumCode,
  useRegisterWithGoogle,
  registerWithGoogle,
  useRegisterUser,
  registerUser,
  useUpdateProfile,
  updateProfile,
  useManagementCompanies,
  useManagementCompaniesPaginated,
  useManagementCompany,
  useManagementCompanyUsageStats,
  useCanCreateResource,
  useMyCompanyCanCreateResource,
  useCreateManagementCompany,
  useUpdateManagementCompany,
  useToggleManagementCompanyActive,
  useCreateUser,
  getManagementCompanies,
  getManagementCompaniesPaginated,
  getManagementCompanyById,
  getManagementCompanyUsageStats,
  getMyCompanyDetail,
  getMyCompanySubscription,
  getMyCompanyUsageStats,
  getMyCompanySubscriptionsPaginated,
  cancelMyCompanySubscription,
  getMyCompanyPreferredCurrency,
  updateMyCompanyPreferredCurrency,
  useUpdateMyCompanyPreferredCurrency,
  useMyCompanyPreferredCurrency,
  createManagementCompany,
  createUser,
  createManagementCompanyWithAdmin,
  toggleManagementCompanyActive,
  updateManagementCompany,
  useLocationsByType,
  useLocationsByParent,
  useLocationById,
  getLocationsByType,
  getLocationsByParent,
  getLocationById,
  getLocationHierarchy,
  createCompanyWithAdmin,
  createCompanyWithExistingAdmin,
  validateInvitationToken,
  acceptInvitation,
  cancelInvitation,
  getInvitationByToken,
  getPendingInvitationsByEmail,
  resendInvitationEmail,
  useManagementCompanySubscription,
  useManagementCompanySubscriptions,
  useManagementCompanySubscriptionsPaginated,
  useCreateSubscription,
  useUpdateSubscription,
  useCancelSubscription,
  useRenewSubscription,
  useSubscriptionPricing,
  getManagementCompanySubscription,
  getManagementCompanySubscriptions,
  getManagementCompanySubscriptionsPaginated,
  createSubscription,
  updateSubscription,
  cancelSubscription,
  renewSubscription,
  getSubscriptionPricing,
  managementCompanySubscriptionKeys,
  useSubscriptionInvoices,
  useSubscriptionInvoice,
  useMarkInvoicePaid,
  getSubscriptionInvoices,
  getSubscriptionInvoice,
  markInvoicePaid,
  downloadInvoicePDF,
  subscriptionInvoiceKeys,
  useManagementCompanyMembers,
  useManagementCompanyMembersPaginated,
  usePrimaryAdmin,
  useAddMember,
  useMyCompanyInviteMember,
  useUpdateMember,
  useUpdateMemberPermissions,
  useRemoveMember,
  getManagementCompanyMembers,
  getManagementCompanyMembersPaginated,
  getPrimaryAdmin,
  addMember,
  updateMember,
  updateMemberPermissions,
  removeMember,
  managementCompanyMemberKeys,
  useMyCompanyMembersPaginated,
  useMyCompanyMemberDetail,
  useMyCompanyMemberAuditLogs,
  useMyCompanyMemberAuditLogsPaginated,
  useMyCompanyMemberAuditLogDetail,
  useMyCompanyUpdateMemberRole,
  useMyCompanyDeactivateMember,
  useMyCompanyReactivateMember,
  // Interest Configurations
  useInterestConfigsByPaymentConcept,
  useCreateInterestConfiguration,
  interestConfigurationKeys,
  // Units (by condominium)
  useCondominiumUnits,
  // Buildings (simple client-side)
  useCondominiumBuildingsList,
  useSupportTickets,
  useSupportTicket,
  useAllSupportTickets,
  useCreateTicket,
  useUpdateTicket,
  useAssignTicket,
  useResolveTicket,
  useCloseTicket,
  useUpdateTicketStatus,
  getSupportTickets,
  getSupportTicket,
  getAllSupportTickets,
  createTicket,
  updateTicket,
  assignTicket,
  resolveTicket,
  closeTicket,
  updateTicketStatus,
  supportTicketKeys,
  useTicketMessages,
  useCreateTicketMessage,
  useDeleteTicketMessage,
  getTicketMessages,
  createTicketMessage,
  deleteTicketMessage,
  supportTicketMessageKeys,
  useTicketWebSocket,
  // User Tickets (resident-facing)
  useMyTickets,
  useCreateUserTicket,
  useUserTicket,
  useUserTicketMessages,
  useCreateUserTicketMessage,
  useUserUpdateTicketStatus,
  useUserResolveTicket,
  useUserCloseTicket,
  userTicketKeys,
  useSuperadminUsersPaginated,
  getSuperadminUsersPaginated,
  useActiveSubscriptionRate,
  useSubscriptionRateByVersion,
  useSubscriptionRate,
  useSubscriptionRates,
  useCreateSubscriptionRate,
  useUpdateSubscriptionRate,
  useActivateSubscriptionRate,
  useDeactivateSubscriptionRate,
  getActiveSubscriptionRate,
  getSubscriptionRateByVersion,
  getSubscriptionRate,
  getSubscriptionRates,
  createSubscriptionRate,
  updateSubscriptionRate,
  activateSubscriptionRate,
  deactivateSubscriptionRate,
  subscriptionRateKeys,
  // Currencies
  useCurrencies,
  useActiveCurrencies,
  useCurrency,
  useBaseCurrency,
  useCreateCurrency,
  useUpdateCurrency,
  useDeleteCurrency,
  getCurrencies,
  getBaseCurrency,
  getCurrency,
  currencyKeys,
  // Exchange Rates
  useExchangeRates,
  useExchangeRatesPaginated,
  useLatestExchangeRates,
  useLatestExchangeRate,
  useExchangeRatesByDate,
  useCreateExchangeRate,
  useDeleteExchangeRate,
  useMyLatestExchangeRates,
  getLatestExchangeRates,
  getExchangeRatesPaginated,
  exchangeRateKeys,
  // Payments
  usePayments,
  usePaymentsPaginated,
  usePaymentsPendingVerification,
  usePaymentByNumber,
  usePaymentsByUser,
  usePaymentsByUnit,
  usePaymentsByStatus,
  usePaymentsByDateRange,
  usePaymentDetail,
  useCreatePayment,
  useReportPayment,
  useVerifyPayment,
  useRejectPayment,
  useRefundPayment,
  useUpdatePayment,
  useDeletePayment,
  getPayments,
  getPaymentsPendingVerification,
  getPaymentByNumber,
  getPaymentsByUser,
  getPaymentsByUserPaginated,
  getPaymentsByUnit,
  getPaymentsByStatus,
  getPaymentsByDateRange,
  getPaymentDetail,
  createPayment,
  reportPayment,
  verifyPayment,
  rejectPayment,
  refundPayment,
  verifyPaymentReference,
  updatePayment,
  deletePayment,
  paymentKeys,
  // Account Statements
  useAccountStatement,
  getAccountStatementServer,
  accountStatementKeys,
  // Delinquency Report
  useDelinquencyReport,
  getDelinquencyReportServer,
  delinquencyKeys,
  // Expenses
  useExpenses,
  useExpensesPendingApproval,
  useExpensesByCondominium,
  useExpensesByBuilding,
  useExpensesByCategory,
  useExpensesByStatus,
  useExpensesByDateRange,
  useExpenseDetail,
  useCreateExpense,
  useUpdateExpense,
  useDeleteExpense,
  getExpenses,
  getExpensesPendingApproval,
  getExpensesByCondominium,
  getExpensesByBuilding,
  getExpensesByCategory,
  getExpensesByStatus,
  getExpensesByDateRange,
  getExpenseDetail,
  createExpense,
  updateExpense,
  deleteExpense,
  expenseKeys,
  // Expense Categories
  useExpenseCategories,
  useExpenseCategoriesRoot,
  useExpenseCategoriesByParent,
  useExpenseCategoryDetail,
  useCreateExpenseCategory,
  useUpdateExpenseCategory,
  useDeleteExpenseCategory,
  getExpenseCategories,
  getExpenseCategoriesRoot,
  getExpenseCategoriesByParent,
  getExpenseCategoryDetail,
  createExpenseCategory,
  updateExpenseCategory,
  deleteExpenseCategory,
  expenseCategoryKeys,
  // Amenities
  useAmenities,
  useAmenitiesByCondominium,
  useAmenityDetail,
  useCreateAmenity,
  useUpdateAmenity,
  useDeleteAmenity,
  getAmenities,
  getAmenitiesByCondominium,
  getAmenityDetail,
  createAmenity,
  updateAmenity,
  deleteAmenity,
  amenityKeys,
  // Amenity Reservations
  useAmenityReservations,
  useReservationsByAmenity,
  useReservationsByUser,
  useReservationDetail,
  useCreateReservation,
  useApproveReservation,
  useRejectReservation,
  useCancelReservation,
  getAmenityReservations,
  getReservationsByAmenity,
  getReservationsByUser,
  getReservationDetail,
  createReservation,
  approveReservation,
  rejectReservation,
  cancelReservation,
  amenityReservationKeys,
  // Subscription Terms & Conditions
  useSubscriptionTermsList,
  useSubscriptionTermsDetail,
  useActiveSubscriptionTerms,
  useCreateSubscriptionTerms,
  useUpdateSubscriptionTerms,
  useDeactivateSubscriptionTerms,
  getSubscriptionTermsList,
  getSubscriptionTermsDetail,
  subscriptionTermsKeys,
  // Reports / Export
  downloadAccountStatement,
  downloadDebtorsReport,
  setReportAuthToken,
  // Banks & Bank Accounts
  useBanks,
  getBanks,
  bankKeys,
  useMyCompanyBankAccountsPaginated,
  useMyCompanyBankAccountDetail,
  useCreateBankAccount,
  useDeactivateBankAccount,
  getMyCompanyBankAccountsPaginated,
  getMyCompanyBankAccountDetail,
  bankAccountKeys,
  // Condominium Services
  useCondominiumServicesPaginated,
  useCondominiumServiceDetail,
  useCreateCondominiumService,
  useUpdateCondominiumService,
  useDeactivateCondominiumService,
  condominiumServiceKeys,
  useQuery,
  useMutation,
  useQueryClient,
  useInfiniteQuery,
  useIsFetching,
  useIsMutating,
  // Wizard Drafts
  useWizardDraft,
  useSaveWizardDraft,
  useDeleteWizardDraft,
  wizardDraftKeys,
  // Bank Reconciliation
  useBankStatementImports,
  useBankStatementEntries,
  useBankReconciliations,
  useBankReconciliationDetail,
  useImportBankStatement,
  useAutoMatch,
  useManualMatch,
  useUnmatchEntry,
  useIgnoreEntry,
  useCreateReconciliation,
  useCompleteReconciliation,
  bankReconciliationKeys,
  // Event Logs
  eventLogKeys,
  useEventLogsPaginated,
  useEventLogDetail,
  type IEventLogsQuery,
  // Assembly Minutes (Fase 5.2)
  assemblyMinuteKeys,
  useAssemblyMinutes,
  useAssemblyMinuteDetail,
  useCreateAssemblyMinute,
  useUpdateAssemblyMinute,
  useDeleteAssemblyMinute,
  // Condominium Board Members
  condominiumBoardKeys,
  useCondominiumBoard,
  useCondominiumBoardDetail,
  useAddBoardMember,
  useUpdateBoardMember,
  useRemoveBoardMember,
  // Charge Categories
  chargeCategoryKeys,
  useChargeCategories,
  useAllChargeCategories,
  // Charge Types (CRUD)
  chargeTypeKeys,
  useChargeTypes,
  useChargeTypeDetail,
  useCreateChargeType,
  useUpdateChargeType,
  useDeleteChargeType,
  // Billing (Fase 5 — Direct Monthly Billing)
  billingChargeKeys,
  useBillingCharges,
  useBillingChargeDetail,
  useCancelCharge,
  useIssueCreditNote,
  useIssueDebitNote,
  chargeDocumentKeys,
  useChargeDocuments,
  useCreateChargeDocument,
  billingReceiptKeys,
  useBillingReceipts,
  useBillingReceiptDetail,
  useVoidBillingReceipt,
  useDownloadBillingReceiptPdf,
  setBillingReceiptDownloadAuth,
  billingLedgerKeys,
  useBillingAccountStatement,
  useUnitBalance,
  useUnitBalanceSummary,
  useSearchUserForOwnership,
  type IBillingAccountStatement,
  type IStatementEntry,
  type IAging,
  type IUnitBalance,
  useReportBillingPayment,
  type IReportBillingPaymentInput,
  // Monthly Billing
  monthlyBillingKeys,
  useBillingConcepts,
  useBillingHistory,
  usePreviewBilling,
  useGenerateBilling,
  type IChargeTypeOption,
  type IUnitChargePreview,
  type IUnitPreview,
  type IPreviewResult,
  type IPreviewInput,
  type IGenerateInput,
  type IGenerateResult,
  type IBillingHistoryItem,
  // Budgets
  useBudgets,
  useBudgetDetail,
  useBudgetCalculateQuotas,
  useBudgetVsActual,
  useCreateBudget,
  useUpdateBudget,
  useDeleteBudget,
  budgetKeys,
} from './hooks/index'
export type {
  QueryProviderProps,
  UseApiQueryOptions,
  UseApiMutationOptions,
  HealthCheckResult,
  UseHealthCheckOptions,
  UseCurrentUserOptions,
  UseUserByFirebaseUidOptions,
  UseUserCondominiumsOptions,
  UseCompanyCondominiumsOptions,
  UseCompanyCondominiumsPaginatedOptions,
  UseCondominiumsOptions,
  UseCondominiumsPaginatedOptions,
  UseCreateCondominiumOptions,
  UseUpdateCondominiumOptions,
  UseGenerateCondominiumCodeOptions,
  TGenerateCondominiumCodeResponse,
  UseRegisterWithGoogleOptions,
  TGoogleRegisterVariables,
  UseRegisterUserOptions,
  TRegisterVariables,
  UseUpdateProfileOptions,
  UseManagementCompaniesOptions,
  UseManagementCompaniesPaginatedOptions,
  UseManagementCompanyOptions,
  UseManagementCompanyUsageStatsOptions,
  UseCanCreateResourceOptions,
  TResourceType,
  TManagementCompanyUsageStats,
  UseCreateManagementCompanyOptions,
  UseUpdateManagementCompanyOptions,
  UseToggleManagementCompanyActiveOptions,
  UseCreateUserOptions,
  TCreateManagementCompanyWithAdminInput,
  TCreateManagementCompanyWithAdminResult,
  TToggleActiveInput,
  UseLocationsByTypeOptions,
  UseLocationsByParentOptions,
  UseLocationByIdOptions,
  TCreateCompanyWithAdminInput,
  TCreateCompanyWithAdminResult,
  TCreateCompanyWithExistingAdminInput,
  TCreateCompanyWithExistingAdminResult,
  TValidateInvitationResult,
  TAcceptInvitationInput,
  TAcceptInvitationResult,
  IUseManagementCompanySubscriptionOptions,
  IUseManagementCompanySubscriptionsOptions,
  IUseManagementCompanySubscriptionsPaginatedOptions,
  ISubscriptionHistoryQuery,
  ICreateSubscriptionOptions,
  IUpdateSubscriptionOptions,
  ICancelSubscriptionOptions,
  IRenewSubscriptionOptions,
  ICancelSubscriptionData,
  IPricingQuery,
  IPricingCalculationResult,
  IUseSubscriptionPricingOptions,
  IInvoiceFilters,
  IUseSubscriptionInvoicesOptions,
  IUseSubscriptionInvoiceOptions,
  IMarkInvoicePaidOptions,
  IMarkInvoicePaidData,
  // Interest Configurations
  ICreateInterestConfigurationOptions,
  IUseManagementCompanyMembersOptions,
  IUseManagementCompanyMembersPaginatedOptions,
  IUsePrimaryAdminOptions,
  IAddMemberOptions,
  IUpdateMemberOptions,
  IUpdateMemberPermissionsOptions,
  IRemoveMemberOptions,
  IUpdateMemberPermissionsData,
  ITicketFilters,
  IUseSupportTicketsOptions,
  IUseSupportTicketOptions,
  ICreateTicketOptions,
  IUpdateTicketOptions,
  IAssignTicketOptions,
  IResolveTicketOptions,
  ICloseTicketOptions,
  IUpdateTicketStatusOptions,
  IAssignTicketData,
  IResolveTicketData,
  ICloseTicketData,
  IUpdateTicketStatusData,
  IUseTicketMessagesOptions,
  ICreateTicketMessageOptions,
  IDeleteTicketMessageOptions,
  // User Tickets types
  IUserTicketFilters,
  ICreateUserTicketInput,
  IUseMyTicketsOptions,
  UseSuperadminUsersPaginatedOptions,
  TSuperadminUserWithDetails,
  TSuperadminUsersQuery,
  IRatesQuery,
  IUseActiveSubscriptionRateOptions,
  IUseSubscriptionRatesOptions,
  IUseSubscriptionRateOptions,
  ICreateSubscriptionRateOptions,
  IUpdateSubscriptionRateOptions,
  IActivateSubscriptionRateOptions,
  IDeactivateSubscriptionRateOptions,
  IUseCurrenciesOptions,
  IUseCurrencyOptions,
  ICreateCurrencyOptions,
  IUpdateCurrencyOptions,
  IDeleteCurrencyOptions,
  IExchangeRatesQuery,
  IUseExchangeRatesOptions,
  ICreateExchangeRateOptions,
  IDeleteExchangeRateOptions,
  IPaymentsQuery,
  IUsePaymentsOptions,
  IUsePaymentDetailOptions,
  ICreatePaymentOptions,
  IReportPaymentOptions,
  IVerifyPaymentOptions,
  IRejectPaymentOptions,
  IRefundPaymentOptions,
  IRefundPaymentData,
  IRefundPaymentResponse,
  IVerifyReferenceData,
  IVerifyReferenceResponse,
  IUpdatePaymentOptions,
  IDeletePaymentOptions,
  IVerifyPaymentData,
  IRejectPaymentData,
  IUseExpenseDetailOptions,
  ICreateExpenseOptions,
  IUpdateExpenseOptions,
  IDeleteExpenseOptions,
  IUseExpenseCategoryDetailOptions,
  ICreateExpenseCategoryOptions,
  IUpdateExpenseCategoryOptions,
  IDeleteExpenseCategoryOptions,
  IUseAmenitiesOptions,
  IUseAmenityDetailOptions,
  ICreateAmenityOptions,
  IUpdateAmenityOptions,
  IDeleteAmenityOptions,
  IUseAmenityReservationsOptions,
  IUseReservationDetailOptions,
  ICreateReservationOptions,
  IApproveReservationOptions,
  IRejectReservationOptions,
  ICancelReservationOptions,
  IRejectReservationData,
  TReportFormat,
  IAccountStatementExportParams,
  IDebtorsReportExportParams,
  ITermsListQuery,
  IUseSubscriptionTermsListOptions,
  IUseSubscriptionTermsDetailOptions,
  ICreateSubscriptionTermsOptions,
  IUpdateSubscriptionTermsOptions,
  IDeactivateSubscriptionTermsOptions,
  // Banks & Bank Accounts
  IUseBanksOptions,
  IUseMyCompanyBankAccountsPaginatedOptions,
  IUseMyCompanyBankAccountDetailOptions,
  ICreateBankAccountOptions,
  IDeactivateBankAccountOptions,
  IDeactivateBankAccountVariables,
  // Condominium Services
  IUseCondominiumServicesPaginatedOptions,
  IUseCondominiumServiceDetailOptions,
  ICreateCondominiumServiceOptions,
  IUpdateCondominiumServiceOptions,
  IUpdateCondominiumServiceVariables,
  IDeactivateCondominiumServiceVariables,
  // Wizard Drafts
  IUseWizardDraftOptions,
  ISaveWizardDraftVariables,
  ISaveWizardDraftOptions,
  IDeleteWizardDraftOptions,
  // Account Statements
  IAccountStatementLineItem,
  IAccountStatementAging,
  IAccountStatementData,
  IAccountStatementQuery,
  // Bank Reconciliation
  IColumnMapping,
  IImportBankStatementInput,
  IImportBankStatementResult,
  IBankStatementImport,
  IBankStatementEntry,
  IAutoMatchResult,
  IManualMatchInput,
  IBankReconciliation,
  ICreateReconciliationInput,
  IReconciliationSummary,
  // Delinquency Report
  IDelinquencyUnit,
  IDelinquencyUnitAging,
  IDelinquencySummary,
  IDelinquencyReportData,
  IDelinquencyReportQuery,
  // Budgets
  IBudgetWithItems,
  ICreateBudgetInput,
  ICreateBudgetItemInput,
  IBudgetVsActualItem,
  IBudgetVsActualResult,
  IUnitQuota,
  ISkippedUnit,
  ICalculateQuotasResult,
  ICreateBudgetOptions,
  IUpdateBudgetOptions,
  IDeleteBudgetOptions,
  // Charge Types
  IChargeTypeCreateInput,
  IChargeTypeUpdateInput,
} from './hooks/index'

// Types
export type {
  HttpMethod,
  RequestConfig,
  ApiResponse,
  ApiError,
  // API Response Types (generic)
  TApiDataResponse,
  TApiMessageResponse,
  TApiDataMessageResponse,
  TValidationFieldError,
  TApiValidationErrorResponse,
  TApiErrorResponse,
  TApiSimpleErrorResponse,
  TApiErrorCode,
  TApiSuccessResponse,
  TApiErrorResponseUnion,
  TApiResponse,
  TApiListResponse,
  TApiEntityResponse,
  TApiCreatedResponse,
  TApiUpdatedResponse,
  TApiDeletedResponse,
  TApiPaginationMeta,
  TApiPaginatedResponse,
  // Entity-specific Response Types
  TEntityListResponse,
  TEntityResponse,
  TEntityCreatedResponse,
  // Users & Authentication
  TUserListResponse,
  TUserResponse,
  TUserCreatedResponse,
  TUserUpdatedResponse,
  TRoleListResponse,
  TRoleResponse,
  TRoleCreatedResponse,
  TRoleUpdatedResponse,
  TPermissionListResponse,
  TPermissionResponse,
  TPermissionCreatedResponse,
  TPermissionUpdatedResponse,
  TRolePermissionListResponse,
  TRolePermissionResponse,
  TRolePermissionCreatedResponse,
  TUserRoleListResponse,
  TUserRoleResponse,
  TUserRoleCreatedResponse,
  // Locations & Currencies
  TLocationListResponse,
  TLocationResponse,
  TLocationCreatedResponse,
  TLocationUpdatedResponse,
  TCurrencyListResponse,
  TCurrencyResponse,
  TCurrencyCreatedResponse,
  TCurrencyUpdatedResponse,
  // Properties
  TManagementCompanyListResponse,
  TManagementCompanyResponse,
  TManagementCompanyCreatedResponse,
  TManagementCompanyUpdatedResponse,
  TCondominiumListResponse,
  TCondominiumResponse,
  TCondominiumCreatedResponse,
  TCondominiumUpdatedResponse,
  TBuildingListResponse,
  TBuildingResponse,
  TBuildingCreatedResponse,
  TBuildingUpdatedResponse,
  TUnitListResponse,
  TUnitResponse,
  TUnitCreatedResponse,
  TUnitUpdatedResponse,
  TUnitOwnershipListResponse,
  TUnitOwnershipResponse,
  TUnitOwnershipCreatedResponse,
  TUnitOwnershipUpdatedResponse,
  // Payments
  TPaymentListResponse,
  TPaymentResponse,
  TPaymentCreatedResponse,
  TPaymentUpdatedResponse,
  TPaymentVerifiedResponse,
  TPaymentGatewayListResponse,
  TPaymentGatewayResponse,
  TPaymentGatewayCreatedResponse,
  TPaymentGatewayUpdatedResponse,
  TEntityPaymentGatewayListResponse,
  TEntityPaymentGatewayResponse,
  TEntityPaymentGatewayCreatedResponse,
  TEntityPaymentGatewayUpdatedResponse,
  TInterestConfigurationListResponse,
  TInterestConfigurationResponse,
  TInterestConfigurationCreatedResponse,
  TInterestConfigurationUpdatedResponse,
  // Expenses
  TExpenseListResponse,
  TExpenseResponse,
  TExpenseCreatedResponse,
  TExpenseUpdatedResponse,
  TExpenseCategoryListResponse,
  TExpenseCategoryResponse,
  TExpenseCategoryCreatedResponse,
  TExpenseCategoryUpdatedResponse,
  TExchangeRateListResponse,
  TExchangeRateResponse,
  TExchangeRateCreatedResponse,
  TExchangeRateUpdatedResponse,
  // Communication
  TDocumentListResponse,
  TDocumentResponse,
  TDocumentCreatedResponse,
  TDocumentUpdatedResponse,
  TMessageListResponse,
  TMessageResponse,
  TMessageCreatedResponse,
  TMessageUpdatedResponse,
  // Notifications
  TNotificationTemplateListResponse,
  TNotificationTemplateResponse,
  TNotificationTemplateCreatedResponse,
  TNotificationTemplateUpdatedResponse,
  TNotificationListResponse,
  TNotificationResponse,
  TNotificationCreatedResponse,
  TNotificationUpdatedResponse,
  TUserNotificationPreferenceListResponse,
  TUserNotificationPreferenceResponse,
  TUserNotificationPreferenceCreatedResponse,
  TUserNotificationPreferenceUpdatedResponse,
  TUserFcmTokenListResponse,
  TUserFcmTokenResponse,
  TUserFcmTokenCreatedResponse,
  TUserFcmTokenUpdatedResponse,
  // Audit
  TAuditLogListResponse,
  TAuditLogResponse,
  // Health
  THealthCheckData,
  THealthCheckResponse,
} from './types/index'

export {
  HttpError,
  // API Response utilities
  ApiErrorCodes,
  isApiDataResponse,
  isApiMessageResponse,
  isApiValidationError,
  isApiErrorResponse,
  isApiSimpleError,
} from './types/index'

// Server utilities
export {
  fetchUserByFirebaseUid,
  syncUserFirebaseUid,
  FetchUserError,
  fetchUserCondominiums,
  fetchUserManagementCompanies,
  fetchSuperadminByUserId,
  fetchSuperadminPermissions,
  fetchSuperadminSession,
  fetchActiveSuperadminUsers,
  fetchNotificationsPaginated,
  fetchUserFcmTokens,
} from './server/index'
export type {
  TSuperadminSession,
  IFetchNotificationsParams,
  IFcmTokenSummary,
} from './server/index'
