'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Check, Eye, Plus, Trash2 } from 'lucide-react'
import {
  useBillingChannelDetail,
  useBillingChannelChargeTypes,
  usePreviewGeneration,
  useGenerateChannelPeriod,
  type IPreviewResult,
} from '@packages/http-client'

import { Typography } from '@/ui/components/typography'
import { Button } from '@/ui/components/button'
import { Input } from '@/ui/components/input'
import { Select, SelectItem } from '@/ui/components/select'
import { Card } from '@/ui/components/card'
import { Spinner } from '@/ui/components/spinner'

interface IGeneratePeriodClientProps {
  channelId: string
}

interface IChargeAmountRow {
  chargeTypeId: string
  amount: string
  description: string
}

const MONTHS = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
]

export function GeneratePeriodClient({ channelId }: IGeneratePeriodClientProps) {
  const router = useRouter()
  const { data: channelData } = useBillingChannelDetail(channelId)
  const { data: chargeTypesData } = useBillingChannelChargeTypes(channelId)

  const channel = channelData?.data
  const chargeTypes = (chargeTypesData?.data ?? []).filter(ct => !ct.isAutoGenerated)

  const now = new Date()
  const [periodYear, setPeriodYear] = useState(now.getFullYear())
  const [periodMonth, setPeriodMonth] = useState(now.getMonth() + 1)
  const [chargeAmounts, setChargeAmounts] = useState<IChargeAmountRow[]>([])
  const [preview, setPreview] = useState<IPreviewResult | null>(null)
  const [generated, setGenerated] = useState(false)

  const previewMutation = usePreviewGeneration(channelId, {
    onSuccess: (res) => setPreview(res.data?.data ?? null),
  })

  const generateMutation = useGenerateChannelPeriod(channelId, {
    onSuccess: () => setGenerated(true),
  })

  // Initialize charge amounts from charge types when they load
  if (chargeTypes.length > 0 && chargeAmounts.length === 0) {
    setChargeAmounts(
      chargeTypes.map(ct => ({
        chargeTypeId: ct.id,
        amount: ct.defaultAmount ?? '',
        description: ct.name,
      }))
    )
  }

  const updateAmount = (index: number, amount: string) => {
    setChargeAmounts(prev => prev.map((ca, i) => (i === index ? { ...ca, amount } : ca)))
    setPreview(null)
  }

  const addRow = () => {
    if (chargeTypes.length === 0) return
    setChargeAmounts(prev => [
      ...prev,
      { chargeTypeId: chargeTypes[0]!.id, amount: '', description: '' },
    ])
  }

  const removeRow = (index: number) => {
    setChargeAmounts(prev => prev.filter((_, i) => i !== index))
    setPreview(null)
  }

  const handlePreview = () => {
    const valid = chargeAmounts.filter(ca => ca.amount && parseFloat(ca.amount) > 0)
    if (valid.length === 0) return
    previewMutation.mutate({
      chargeAmounts: valid.map(ca => ({ chargeTypeId: ca.chargeTypeId, amount: ca.amount })),
    })
  }

  const handleGenerate = () => {
    const valid = chargeAmounts.filter(ca => ca.amount && parseFloat(ca.amount) > 0)
    if (valid.length === 0) return
    generateMutation.mutate({
      periodYear,
      periodMonth,
      chargeAmounts: valid.map(ca => ({
        chargeTypeId: ca.chargeTypeId,
        amount: ca.amount,
        description: ca.description || undefined,
      })),
    })
  }

  if (generated) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center">
        <Check className="mb-4 h-16 w-16 text-green-500" />
        <Typography variant="h2">Recibos Generados</Typography>
        <Typography className="mt-2" color="muted">
          Se generaron los recibos para {MONTHS[periodMonth - 1]} {periodYear}
        </Typography>
        <div className="mt-6 flex gap-3">
          <Button onPress={() => router.push('/dashboard/billing-receipts')}>
            Ver Recibos
          </Button>
          <Button variant="flat" onPress={() => router.push(`/dashboard/billing-channels/${channelId}`)}>
            Volver al Canal
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <Typography variant="h2">Generar Periodo</Typography>
        <Typography className="mt-1" color="muted">
          {channel?.name ?? 'Canal'} — Define los montos del mes y genera los recibos
        </Typography>
      </div>

      {/* Period selector */}
      <div className="flex gap-4">
        <Select
          label="Mes"
          selectedKeys={[String(periodMonth)]}
          onSelectionChange={(keys) => setPeriodMonth(Number(Array.from(keys)[0]))}
          className="w-40"
        >
          {MONTHS.map((name, i) => (
            <SelectItem key={String(i + 1)}>
              {name}
            </SelectItem>
          ))}
        </Select>
        <Input
          label="Ano"
          type="number"
          value={String(periodYear)}
          onChange={(e) => setPeriodYear(Number(e.target.value))}
          className="w-32"
        />
      </div>

      {/* Charge amounts table */}
      <Card className="p-4">
        <Typography variant="h3" className="mb-4">Montos por Tipo de Cargo</Typography>
        <div className="space-y-3">
          {chargeAmounts.map((ca, index) => {
            const ct = chargeTypes.find(t => t.id === ca.chargeTypeId)
            return (
              <div key={index} className="flex items-end gap-3">
                <Select
                  label="Tipo"
                  selectedKeys={[ca.chargeTypeId]}
                  onSelectionChange={(keys) => {
                    const newId = Array.from(keys)[0] as string
                    setChargeAmounts(prev =>
                      prev.map((row, i) => i === index ? { ...row, chargeTypeId: newId } : row)
                    )
                  }}
                  className="flex-1"
                >
                  {chargeTypes.map(ct => (
                    <SelectItem key={ct.id}>{ct.name}</SelectItem>
                  ))}
                </Select>
                <Input
                  label="Monto Total"
                  type="number"
                  value={ca.amount}
                  onChange={(e) => updateAmount(index, e.target.value)}
                  className="w-48"
                  placeholder="0.00"
                />
                <Input
                  label="Descripcion"
                  value={ca.description}
                  onChange={(e) => {
                    setChargeAmounts(prev =>
                      prev.map((row, i) => i === index ? { ...row, description: e.target.value } : row)
                    )
                  }}
                  className="flex-1"
                  placeholder={ct?.name ?? ''}
                />
                <Button
                  isIconOnly
                  variant="flat"
                  color="danger"
                  size="sm"
                  onPress={() => removeRow(index)}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            )
          })}
        </div>
        <Button
          className="mt-3"
          variant="flat"
          size="sm"
          startContent={<Plus className="h-4 w-4" />}
          onPress={addRow}
        >
          Agregar Linea
        </Button>
      </Card>

      {/* Actions */}
      <div className="flex gap-3">
        <Button
          variant="flat"
          startContent={<Eye className="h-4 w-4" />}
          onPress={handlePreview}
          isLoading={previewMutation.isPending}
        >
          Preview Distribucion
        </Button>
        <Button
          color="primary"
          startContent={<Check className="h-4 w-4" />}
          onPress={handleGenerate}
          isLoading={generateMutation.isPending}
          isDisabled={!preview}
        >
          Confirmar y Generar
        </Button>
      </div>

      {/* Preview table */}
      {preview && (
        <Card className="p-4">
          <Typography variant="h3" className="mb-3">
            Preview — Distribucion por Unidad
          </Typography>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="py-2 text-left">Unidad</th>
                  <th className="py-2 text-right">Alicuota</th>
                  {preview.unitPreviews[0]?.charges.map(c => (
                    <th key={c.chargeTypeId} className="py-2 text-right">{c.chargeTypeName}</th>
                  ))}
                  <th className="py-2 text-right font-bold">Total</th>
                </tr>
              </thead>
              <tbody>
                {preview.unitPreviews.map(up => (
                  <tr key={up.unitId} className="border-b border-default-100">
                    <td className="py-2">{up.unitNumber}</td>
                    <td className="py-2 text-right">{up.aliquotPercentage}%</td>
                    {up.charges.map(c => (
                      <td key={c.chargeTypeId} className="py-2 text-right">{c.amount}</td>
                    ))}
                    <td className="py-2 text-right font-bold">{up.total}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2">
                  <td className="py-2 font-bold">Total</td>
                  <td className="py-2 text-right">{preview.aliquotSum}%</td>
                  <td colSpan={99} className="py-2 text-right font-bold">{preview.grandTotal}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </Card>
      )}
    </div>
  )
}
