export { createQueryClient, getQueryClient, setQueryClient } from './query-client'
export { QueryProvider, type QueryProviderProps } from './query-provider'
export {
  useApiQuery,
  useApiMutation,
  type UseApiQueryOptions,
  type UseApiMutationOptions,
} from './use-api-query'
export {
  useHealthCheck,
  type HealthCheckResult,
  type UseHealthCheckOptions,
} from './use-health-check'
export {
  useCurrentUser,
  useUserByFirebaseUid,
  getUserByEmail,
  type UseCurrentUserOptions,
  type UseUserByFirebaseUidOptions,
} from './use-user'
export { useUserCondominiums, type UseUserCondominiumsOptions } from './use-user-condominiums'
export {
  useCompanyCondominiums,
  useCompanyCondominiumsPaginated,
  getCompanyCondominiums,
  getCompanyCondominiumsPaginated,
  companyCondominiumsKeys,
  type UseCompanyCondominiumsOptions,
  type UseCompanyCondominiumsPaginatedOptions,
} from './use-company-condominiums'
export {
  useCondominiums,
  useCondominiumsPaginated,
  useCreateCondominium,
  useUpdateCondominium,
  useGenerateCondominiumCode,
  condominiumsKeys,
  getAllCondominiums,
  getCondominiumsPaginated,
  createCondominium,
  updateCondominium,
  generateCondominiumCode,
  type UseCondominiumsOptions,
  type UseCondominiumsPaginatedOptions,
  type UseCreateCondominiumOptions,
  type UseUpdateCondominiumOptions,
  type UseGenerateCondominiumCodeOptions,
  type TGenerateCondominiumCodeResponse,
} from './use-condominiums'
export {
  useCondominiumDetail,
  getCondominiumDetail,
  type UseCondominiumDetailOptions,
} from './use-condominium-detail'
export {
  useToggleCondominiumStatus,
  type UseToggleCondominiumStatusOptions,
  type TToggleCondominiumStatusVariables,
} from './use-toggle-condominium-status'
export {
  useCondominiumBuildings,
  useBuildingDetail,
  useCreateBuilding,
  useUpdateBuilding,
  useDeleteBuilding,
  useToggleBuildingStatus,
  getCondominiumBuildings,
  getBuildingDetail,
  buildingsKeys,
  type UseCondominiumBuildingsOptions,
  type UseBuildingDetailOptions,
  type UseCreateBuildingOptions,
  type UseUpdateBuildingOptions,
  type UseDeleteBuildingOptions,
  type UseToggleBuildingStatusOptions,
  type TCreateBuildingVariables,
  type TUpdateBuildingVariables,
  type TDeleteBuildingVariables,
  type TToggleBuildingStatusVariables,
} from './use-buildings'
export {
  useBuildingUnits,
  useUnitDetail,
  useCreateUnit,
  useUpdateUnit,
  useDeleteUnit,
  useToggleUnitStatus,
  getBuildingUnits,
  getUnitDetail,
  unitsKeys,
  type UseBuildingUnitsOptions,
  type UseUnitDetailOptions,
  type UseCreateUnitOptions,
  type UseUpdateUnitOptions,
  type UseDeleteUnitOptions,
  type UseToggleUnitStatusOptions,
  type TCreateUnitVariables,
  type TUpdateUnitVariables,
  type TDeleteUnitVariables,
  type TToggleUnitStatusVariables,
} from './use-units'
export {
  useCondominiumUsers,
  useAddUserToCondominium,
  useRemoveUserFromCondominium,
  useUpdateUserCondominiumRole,
  useAssignUnitToUser,
  useRemoveUnitFromUser,
  getCondominiumUsers,
  condominiumUsersKeys,
  type TCondominiumUser,
  type TCondominiumUserRole,
  type TCondominiumUserUnit,
  type UseCondominiumUsersOptions,
  type UseAddUserToCondominiumOptions,
  type UseRemoveUserFromCondominiumOptions,
  type UseUpdateUserRoleOptions,
  type UseAssignUnitToUserOptions,
  type UseRemoveUnitFromUserOptions,
  type TAddUserToCondominiumVariables,
  type TRemoveUserFromCondominiumVariables,
  type TUpdateUserRoleVariables,
  type TAssignUnitToUserVariables,
  type TRemoveUnitFromUserVariables,
} from './use-condominium-users'
export {
  useRegisterWithGoogle,
  registerWithGoogle,
  useRegisterUser,
  registerUser,
  type UseRegisterWithGoogleOptions,
  type TGoogleRegisterVariables,
  type UseRegisterUserOptions,
  type TRegisterVariables,
} from './use-auth'
export { useUpdateProfile, updateProfile, type UseUpdateProfileOptions } from './use-update-profile'
export {
  useManagementCompanies,
  useManagementCompaniesPaginated,
  useManagementCompany,
  useManagementCompanyUsageStats,
  useCanCreateResource,
  useCreateManagementCompany,
  useUpdateManagementCompany,
  useToggleManagementCompanyActive,
  useCreateUser,
  getManagementCompanies,
  getManagementCompaniesPaginated,
  getManagementCompanyById,
  getManagementCompanyUsageStats,
  createManagementCompany,
  createUser,
  createManagementCompanyWithAdmin,
  toggleManagementCompanyActive,
  updateManagementCompany,
  type UseManagementCompaniesOptions,
  type UseManagementCompaniesPaginatedOptions,
  type UseManagementCompanyOptions,
  type UseManagementCompanyUsageStatsOptions,
  type UseCanCreateResourceOptions,
  type TResourceType,
  type TManagementCompanyUsageStats,
  type UseCreateManagementCompanyOptions,
  type UseUpdateManagementCompanyOptions,
  type UseToggleManagementCompanyActiveOptions,
  type UseCreateUserOptions,
  type TCreateManagementCompanyWithAdminInput,
  type TCreateManagementCompanyWithAdminResult,
  type TToggleActiveInput,
} from './use-management-companies'
export {
  useLocationsByType,
  useLocationsByParent,
  useLocationById,
  getLocationsByType,
  getLocationsByParent,
  getLocationById,
  getLocationHierarchy,
  type UseLocationsByTypeOptions,
  type UseLocationsByParentOptions,
  type UseLocationByIdOptions,
} from './use-locations'
export {
  createCompanyWithAdmin,
  validateInvitationToken,
  acceptInvitation,
  cancelInvitation,
  getInvitationByToken,
  getPendingInvitationsByEmail,
  resendInvitationEmail,
  type TCreateCompanyWithAdminInput,
  type TCreateCompanyWithAdminResult,
  type TValidateInvitationResult,
  type TAcceptInvitationInput,
  type TAcceptInvitationResult,
} from './use-admin-invitations'
export {
  useManagementCompanySubscription,
  useManagementCompanySubscriptions,
  useManagementCompanySubscriptionsPaginated,
  useCreateSubscription,
  useUpdateSubscription,
  useCancelSubscription,
  useRenewSubscription,
  useSubscriptionPricing,
  getManagementCompanySubscription,
  getManagementCompanySubscriptions,
  getManagementCompanySubscriptionsPaginated,
  createSubscription,
  updateSubscription,
  cancelSubscription,
  renewSubscription,
  getSubscriptionPricing,
  managementCompanySubscriptionKeys,
  type IUseManagementCompanySubscriptionOptions,
  type IUseManagementCompanySubscriptionsOptions,
  type IUseManagementCompanySubscriptionsPaginatedOptions,
  type ISubscriptionHistoryQuery,
  type ICreateSubscriptionOptions,
  type IUpdateSubscriptionOptions,
  type ICancelSubscriptionOptions,
  type IRenewSubscriptionOptions,
  type ICancelSubscriptionData,
  type IPricingQuery,
  type IPricingCalculationResult,
  type IUseSubscriptionPricingOptions,
} from './use-management-company-subscriptions'
export {
  useSubscriptionInvoices,
  useSubscriptionInvoice,
  useMarkInvoicePaid,
  getSubscriptionInvoices,
  getSubscriptionInvoice,
  markInvoicePaid,
  downloadInvoicePDF,
  subscriptionInvoiceKeys,
  type IInvoiceFilters,
  type IUseSubscriptionInvoicesOptions,
  type IUseSubscriptionInvoiceOptions,
  type IMarkInvoicePaidOptions,
  type IMarkInvoicePaidData,
} from './use-subscription-invoices'
export {
  useManagementCompanyMembers,
  useManagementCompanyMembersPaginated,
  usePrimaryAdmin,
  useAddMember,
  useUpdateMember,
  useUpdateMemberPermissions,
  useRemoveMember,
  getManagementCompanyMembers,
  getManagementCompanyMembersPaginated,
  getPrimaryAdmin,
  addMember,
  updateMember,
  updateMemberPermissions,
  removeMember,
  managementCompanyMemberKeys,
  type IUseManagementCompanyMembersOptions,
  type IUseManagementCompanyMembersPaginatedOptions,
  type IUsePrimaryAdminOptions,
  type IAddMemberOptions,
  type IUpdateMemberOptions,
  type IUpdateMemberPermissionsOptions,
  type IRemoveMemberOptions,
  type IUpdateMemberPermissionsData,
} from './use-management-company-members'
export {
  useSupportTickets,
  useSupportTicket,
  useAllSupportTickets,
  useCreateTicket,
  useUpdateTicket,
  useAssignTicket,
  useResolveTicket,
  useCloseTicket,
  useUpdateTicketStatus,
  getSupportTickets,
  getSupportTicket,
  getAllSupportTickets,
  createTicket,
  updateTicket,
  assignTicket,
  resolveTicket,
  closeTicket,
  updateTicketStatus,
  supportTicketKeys,
  type ITicketFilters,
  type IUseSupportTicketsOptions,
  type IUseSupportTicketOptions,
  type ICreateTicketOptions,
  type IUpdateTicketOptions,
  type IAssignTicketOptions,
  type IResolveTicketOptions,
  type ICloseTicketOptions,
  type IUpdateTicketStatusOptions,
  type IAssignTicketData,
  type IResolveTicketData,
  type ICloseTicketData,
  type IUpdateTicketStatusData,
} from './use-support-tickets'
export {
  useTicketMessages,
  useCreateTicketMessage,
  useDeleteTicketMessage,
  getTicketMessages,
  createTicketMessage,
  deleteTicketMessage,
  supportTicketMessageKeys,
  type IUseTicketMessagesOptions,
  type ICreateTicketMessageOptions,
  type IDeleteTicketMessageOptions,
} from './use-support-ticket-messages'
export { useTicketWebSocket } from './use-ticket-websocket'
export {
  useSuperadminUsersPaginated,
  getSuperadminUsersPaginated,
  type UseSuperadminUsersPaginatedOptions,
  type TSuperadminUserWithDetails,
  type TSuperadminUsersQuery,
} from './use-superadmin-users'
export {
  useUsersPaginated,
  useUserFullDetails,
  useRoles,
  useToggleUserPermission,
  useBatchToggleUserPermissions,
  getUsersPaginated,
  getUserFullDetails,
  getAllRoles,
  updateUserStatus,
  updateUserRoleStatus,
  toggleUserPermission,
  usersKeys,
  type TUsersQuery,
  type TUserWithRoles,
  type TUserRoleSummary,
  type TUserFullDetails,
  type TUserRoleDetail,
  type TCondominiumWithRoles,
  type TSuperadminPermissionDetail,
  type TRoleOption,
  type UseUsersPaginatedOptions,
  type UseUserFullDetailsOptions,
  type UseRolesOptions,
  type IToggleUserPermissionVariables,
  type IUseToggleUserPermissionOptions,
  type IBatchToggleUserPermissionsVariables,
  type IBatchToggleUserPermissionsResponse,
  type IUseBatchToggleUserPermissionsOptions,
} from './use-users'
export {
  createUserInvitation,
  createUserWithInvitation,
  validateUserInvitationToken,
  acceptUserInvitation,
  resendUserInvitationEmail,
  cancelUserInvitation,
  type TCreateUserInvitationInput,
  type TCreateUserWithInvitationInput,
  type TInvitationUser,
  type TUserInvitation,
  type TInvitationUserRole,
  type TInvitationUserPermission,
  type TCreateUserInvitationResult,
  type TCreateUserWithInvitationResult,
  type TValidationCondominium,
  type TValidationRole,
  type TValidateUserInvitationResult,
  type TAcceptUserInvitationResult,
} from './use-user-invitations'
export {
  useRoleByName,
  useAssignableRoles,
  useAllRoles as useAllRolesQuery,
  useSystemRoles,
  getRoleByName,
  getAssignableRoles,
  getAllRoles as getAllRolesQuery,
  getSystemRoles,
  rolesKeys,
  type UseRoleByNameOptions,
  type UseAssignableRolesOptions,
  type UseAllRolesOptions,
  type UseSystemRolesOptions,
} from './use-roles'
export {
  useAllPermissions,
  useRolePermissions,
  usePermissionsByModule,
  getAllPermissions,
  getRolePermissions,
  getPermissionsByModule,
  permissionsKeys,
  type UseAllPermissionsOptions,
  type UseRolePermissionsOptions,
  type UsePermissionsByModuleOptions,
  type TPermissionDetail,
} from './use-permissions'
export {
  promoteUserToSuperadmin,
  demoteUserFromSuperadmin,
  usePromoteToSuperadmin,
  useDemoteFromSuperadmin,
  type IPromoteToSuperadminPayload,
  type IPromoteToSuperadminVariables,
  type IDemoteFromSuperadminVariables,
  type IUsePromoteToSuperadminOptions,
  type IUseDemoteFromSuperadminOptions,
} from './use-superadmin-promotion'
export {
  useActiveSubscriptionRate,
  useSubscriptionRateByVersion,
  useSubscriptionRate,
  useSubscriptionRates,
  useCreateSubscriptionRate,
  useUpdateSubscriptionRate,
  useActivateSubscriptionRate,
  useDeactivateSubscriptionRate,
  getActiveSubscriptionRate,
  getSubscriptionRateByVersion,
  getSubscriptionRate,
  getSubscriptionRates,
  createSubscriptionRate,
  updateSubscriptionRate,
  activateSubscriptionRate,
  deactivateSubscriptionRate,
  subscriptionRateKeys,
  type IRatesQuery,
  type IUseActiveSubscriptionRateOptions,
  type IUseSubscriptionRatesOptions,
  type IUseSubscriptionRateOptions,
  type ICreateSubscriptionRateOptions,
  type IUpdateSubscriptionRateOptions,
  type IActivateSubscriptionRateOptions,
  type IDeactivateSubscriptionRateOptions,
} from './use-subscription-rates'

// Re-export commonly used TanStack Query hooks
export {
  useQuery,
  useMutation,
  useQueryClient,
  useInfiniteQuery,
  useIsFetching,
  useIsMutating,
} from '@tanstack/react-query'
