export { createQueryClient, getQueryClient, setQueryClient } from './query-client'
export { QueryProvider, type QueryProviderProps } from './query-provider'
export {
  useApiQuery,
  useApiMutation,
  type UseApiQueryOptions,
  type UseApiMutationOptions,
} from './use-api-query'
export {
  useHealthCheck,
  type HealthCheckResult,
  type UseHealthCheckOptions,
} from './use-health-check'
export {
  useCurrentUser,
  useUserByFirebaseUid,
  getUserByEmail,
  type UseCurrentUserOptions,
  type UseUserByFirebaseUidOptions,
} from './use-user'
export { useUserCondominiums, type UseUserCondominiumsOptions } from './use-user-condominiums'
export {
  useCompanyCondominiums,
  companyCondominiumsKeys,
  type UseCompanyCondominiumsOptions,
} from './use-company-condominiums'
export {
  useCondominiums,
  useCondominiumsPaginated,
  condominiumsKeys,
  getAllCondominiums,
  getCondominiumsPaginated,
  type UseCondominiumsOptions,
  type UseCondominiumsPaginatedOptions,
} from './use-condominiums'
export {
  useRegisterWithGoogle,
  registerWithGoogle,
  useRegisterUser,
  registerUser,
  type UseRegisterWithGoogleOptions,
  type TGoogleRegisterVariables,
  type UseRegisterUserOptions,
  type TRegisterVariables,
} from './use-auth'
export { useUpdateProfile, updateProfile, type UseUpdateProfileOptions } from './use-update-profile'
export {
  useManagementCompanies,
  useManagementCompaniesPaginated,
  useManagementCompany,
  useCreateManagementCompany,
  useUpdateManagementCompany,
  useToggleManagementCompanyActive,
  useCreateUser,
  getManagementCompanies,
  getManagementCompaniesPaginated,
  getManagementCompanyById,
  createManagementCompany,
  createUser,
  createManagementCompanyWithAdmin,
  toggleManagementCompanyActive,
  updateManagementCompany,
  type UseManagementCompaniesOptions,
  type UseManagementCompaniesPaginatedOptions,
  type UseManagementCompanyOptions,
  type UseCreateManagementCompanyOptions,
  type UseUpdateManagementCompanyOptions,
  type UseToggleManagementCompanyActiveOptions,
  type UseCreateUserOptions,
  type TCreateManagementCompanyWithAdminInput,
  type TCreateManagementCompanyWithAdminResult,
  type TToggleActiveInput,
} from './use-management-companies'
export {
  useLocationsByType,
  useLocationsByParent,
  useLocationById,
  getLocationsByType,
  getLocationsByParent,
  getLocationById,
  getLocationHierarchy,
  type UseLocationsByTypeOptions,
  type UseLocationsByParentOptions,
  type UseLocationByIdOptions,
} from './use-locations'
export {
  createCompanyWithAdmin,
  validateInvitationToken,
  acceptInvitation,
  cancelInvitation,
  getInvitationByToken,
  getPendingInvitationsByEmail,
  resendInvitationEmail,
  type TCreateCompanyWithAdminInput,
  type TCreateCompanyWithAdminResult,
  type TValidateInvitationResult,
  type TAcceptInvitationInput,
  type TAcceptInvitationResult,
} from './use-admin-invitations'
export {
  useManagementCompanySubscription,
  useManagementCompanySubscriptions,
  useCreateSubscription,
  useUpdateSubscription,
  useCancelSubscription,
  useRenewSubscription,
  getManagementCompanySubscription,
  getManagementCompanySubscriptions,
  createSubscription,
  updateSubscription,
  cancelSubscription,
  renewSubscription,
  managementCompanySubscriptionKeys,
  type IUseManagementCompanySubscriptionOptions,
  type IUseManagementCompanySubscriptionsOptions,
  type ICreateSubscriptionOptions,
  type IUpdateSubscriptionOptions,
  type ICancelSubscriptionOptions,
  type IRenewSubscriptionOptions,
  type ICancelSubscriptionData,
} from './use-management-company-subscriptions'
export {
  useSubscriptionInvoices,
  useSubscriptionInvoice,
  useMarkInvoicePaid,
  getSubscriptionInvoices,
  getSubscriptionInvoice,
  markInvoicePaid,
  downloadInvoicePDF,
  subscriptionInvoiceKeys,
  type IInvoiceFilters,
  type IUseSubscriptionInvoicesOptions,
  type IUseSubscriptionInvoiceOptions,
  type IMarkInvoicePaidOptions,
  type IMarkInvoicePaidData,
} from './use-subscription-invoices'
export {
  useManagementCompanyMembers,
  usePrimaryAdmin,
  useAddMember,
  useUpdateMember,
  useUpdateMemberPermissions,
  useRemoveMember,
  getManagementCompanyMembers,
  getPrimaryAdmin,
  addMember,
  updateMember,
  updateMemberPermissions,
  removeMember,
  managementCompanyMemberKeys,
  type IUseManagementCompanyMembersOptions,
  type IUsePrimaryAdminOptions,
  type IAddMemberOptions,
  type IUpdateMemberOptions,
  type IUpdateMemberPermissionsOptions,
  type IRemoveMemberOptions,
  type IUpdateMemberPermissionsData,
} from './use-management-company-members'
export {
  useSupportTickets,
  useSupportTicket,
  useAllSupportTickets,
  useCreateTicket,
  useUpdateTicket,
  useAssignTicket,
  useResolveTicket,
  useCloseTicket,
  useUpdateTicketStatus,
  getSupportTickets,
  getSupportTicket,
  getAllSupportTickets,
  createTicket,
  updateTicket,
  assignTicket,
  resolveTicket,
  closeTicket,
  updateTicketStatus,
  supportTicketKeys,
  type ITicketFilters,
  type IUseSupportTicketsOptions,
  type IUseSupportTicketOptions,
  type ICreateTicketOptions,
  type IUpdateTicketOptions,
  type IAssignTicketOptions,
  type IResolveTicketOptions,
  type ICloseTicketOptions,
  type IUpdateTicketStatusOptions,
  type IAssignTicketData,
  type IResolveTicketData,
  type ICloseTicketData,
  type IUpdateTicketStatusData,
} from './use-support-tickets'
export {
  useTicketMessages,
  useCreateTicketMessage,
  useDeleteTicketMessage,
  getTicketMessages,
  createTicketMessage,
  deleteTicketMessage,
  supportTicketMessageKeys,
  type IUseTicketMessagesOptions,
  type ICreateTicketMessageOptions,
  type IDeleteTicketMessageOptions,
} from './use-support-ticket-messages'
export { useTicketWebSocket } from './use-ticket-websocket'
export {
  useSuperadminUsersPaginated,
  getSuperadminUsersPaginated,
  type UseSuperadminUsersPaginatedOptions,
  type TSuperadminUserWithDetails,
  type TSuperadminUsersQuery,
} from './use-superadmin-users'
export {
  useUsersPaginated,
  useUserFullDetails,
  useRoles,
  getUsersPaginated,
  getUserFullDetails,
  getAllRoles,
  updateUserStatus,
  updateUserRoleStatus,
  toggleUserPermission,
  usersKeys,
  type TUsersQuery,
  type TUserWithRoles,
  type TUserRoleSummary,
  type TUserFullDetails,
  type TUserRoleDetail,
  type TCondominiumWithRoles,
  type TSuperadminPermissionDetail,
  type TRoleOption,
  type UseUsersPaginatedOptions,
  type UseUserFullDetailsOptions,
  type UseRolesOptions,
} from './use-users'
export {
  createUserInvitation,
  validateUserInvitationToken,
  acceptUserInvitation,
  resendUserInvitationEmail,
  cancelUserInvitation,
  type TCreateUserInvitationInput,
  type TInvitationUser,
  type TUserInvitation,
  type TInvitationUserRole,
  type TCreateUserInvitationResult,
  type TValidationCondominium,
  type TValidationRole,
  type TValidateUserInvitationResult,
  type TAcceptUserInvitationResult,
} from './use-user-invitations'

// Re-export commonly used TanStack Query hooks
export {
  useQuery,
  useMutation,
  useQueryClient,
  useInfiniteQuery,
  useIsFetching,
  useIsMutating,
} from '@tanstack/react-query'
